import { describe, expect, it } from 'vitest';
import { formatThaiDate } from '../src/thaiDate';
import dateGolden from './fixtures/thai-date-golden.json';

/**
 * thaiDate.test.ts — DB-free tests for formatThaiDate.
 *
 * fixtures/thai-date-golden.json was generated by executing the real
 * `includes/document-helpers.php` source (unmodified) via a `php` CLI
 * (PHP 8.4) across 400 random dates spanning 1990-2035 (both short/long
 * variants each) plus explicit leap-day/year-boundary/malformed-input
 * cases — see docs/runbooks/phase5-documents-vat-parity.md.
 */

interface DateGoldenRow {
  input: string;
  short: boolean;
  expected: string;
}

const dateCases = dateGolden as DateGoldenRow[];

describe('formatThaiDate — golden fixture parity with real PHP formatThaiDate()', () => {
  it('fixture has 400+ cases spanning a wide year range', () => {
    expect(dateCases.length).toBeGreaterThan(400);
  });

  it('matches real-PHP output exactly for every fixture row', () => {
    const mismatches: unknown[] = [];
    for (const c of dateCases) {
      const got = formatThaiDate(c.input, c.short);
      if (got !== c.expected) mismatches.push({ ...c, got });
    }
    expect(mismatches).toEqual([]);
  });
});

describe('formatThaiDate — explicit named cases (acceptance criteria)', () => {
  it('leap day: 2024-02-29 (a real Gregorian leap day) -> Buddhist year 2567', () => {
    expect(formatThaiDate('2024-02-29', true)).toBe('29 ก.พ. 2567');
    expect(formatThaiDate('2024-02-29', false)).toBe('29 กุมภาพันธ์ 2567');
  });

  it('year boundary: 2024-12-31 / 2025-01-01', () => {
    expect(formatThaiDate('2024-12-31', true)).toBe('31 ธ.ค. 2567');
    expect(formatThaiDate('2025-01-01', true)).toBe('1 ม.ค. 2568');
  });

  it('non-leap-year Feb 29 rolls over to Mar 1 (matches PHP calendar rollover)', () => {
    expect(formatThaiDate('2023-02-29', true)).toBe('1 มี.ค. 2566');
  });

  it("'' returns '-'", () => {
    expect(formatThaiDate('')).toBe('-');
  });

  it("'0000-00-00' returns '-'", () => {
    expect(formatThaiDate('0000-00-00')).toBe('-');
  });

  it('unparseable input returns the input untouched', () => {
    expect(formatThaiDate('not-a-date')).toBe('not-a-date');
    expect(formatThaiDate('banana')).toBe('banana');
    expect(formatThaiDate('2024-13-45')).toBe('2024-13-45'); // month/day tokens out of PHP's tokenizer range
    expect(formatThaiDate('2024-01-32')).toBe('2024-01-32'); // day=32 rejected (day token range is 00-31)
  });

  it('short vs long month labels differ, same day/year', () => {
    expect(formatThaiDate('2026-05-24', true)).toBe('24 พ.ค. 2569');
    expect(formatThaiDate('2026-05-24', false)).toBe('24 พฤษภาคม 2569');
  });

  it('defaults to short=true when the second argument is omitted', () => {
    expect(formatThaiDate('2026-05-24')).toBe('24 พ.ค. 2569');
  });
});
