import { describe, expect, it } from 'vitest';
import { calcVAT, computeLineTotal, formatMoney } from '../src/vat';
import vatGolden from './fixtures/vat-golden.json';
import lineTotalGolden from './fixtures/line-total-golden.json';
import moneyGolden from './fixtures/money-golden.json';

/**
 * vat.test.ts — DB-free tests for calcVAT/computeLineTotal/formatMoney.
 *
 * GOLDEN FIXTURES: fixtures/{vat,line-total,money}-golden.json were
 * generated by actually EXECUTING the real `includes/document-helpers.php`
 * source (unmodified, read-only) via a `php` CLI (PHP 8.4) against
 * thousands of randomly-generated inputs plus known floating-point edge
 * cases (1.005, 2.675, 5.055, 100.005, negative amounts, values needing
 * the full 15-significant-digit budget, etc.) — see
 * docs/runbooks/phase5-documents-vat-parity.md for the exact generator
 * scripts and how to regenerate them. This is the strongest fidelity
 * evidence available short of shelling out to PHP at test time (which
 * would make the fast suite depend on a `php` binary being present in
 * whatever sandbox runs `pnpm turbo run test` — deliberately avoided).
 */

interface VatGoldenRow {
  subtotal: number;
  rate: number;
  inclusive: boolean;
  base: number;
  vat: number;
  total: number;
}

interface LineTotalGoldenRow {
  qty: number;
  unit: number;
  discPct: number;
  discAmt: number;
  expected: number;
}

interface MoneyGoldenRow {
  v: number;
  expected: string;
}

const vatCases = vatGolden as VatGoldenRow[];
const lineTotalCases = lineTotalGolden as LineTotalGoldenRow[];
const moneyCases = moneyGolden as MoneyGoldenRow[];

describe('calcVAT — golden fixture parity with real PHP calcVAT()', () => {
  it('fixture has at least 1,000 cases covering both the inclusive and exclusive paths', () => {
    expect(vatCases.length).toBeGreaterThanOrEqual(1000);
    const inclusiveCount = vatCases.filter((c) => c.inclusive).length;
    const exclusiveCount = vatCases.filter((c) => !c.inclusive).length;
    expect(inclusiveCount).toBeGreaterThan(400);
    expect(exclusiveCount).toBeGreaterThan(400);
  });

  it('matches real-PHP output exactly (to the satang) for every fixture row', () => {
    const mismatches: unknown[] = [];
    for (const c of vatCases) {
      const got = calcVAT(c.subtotal, c.rate, c.inclusive);
      if (got.base !== c.base || got.vat !== c.vat || got.total !== c.total) {
        mismatches.push({ input: c, got });
      }
    }
    expect(mismatches).toEqual([]);
  });

  it('classic floating-point edge cases round correctly (1.005 * 7% style inputs)', () => {
    // subtotal=1.005 exclusive, rate=7 -> vat = round(1.005*0.07,2) = round(0.07035,2) = 0.07
    const r = calcVAT(1.005, 7, false);
    expect(r.base).toBe(1.01); // round(1.005,2) via the same phpRound used internally... actually base=subtotal unrounded pre-round
    expect(r.vat).toBeCloseTo(0.07, 5);
  });

  it('negative vatRate is clamped to 0 (matches PHP\'s max(0.0, $vatRate))', () => {
    const r = calcVAT(100, -5, false);
    expect(r).toEqual({ base: 100, vat: 0, total: 100 });
  });

  it('inclusive back-calc: base + vat === total (to the satang) for a spread of rates', () => {
    for (const rate of [0, 3, 7, 10, 15.5]) {
      const r = calcVAT(1070, rate, true);
      expect(Math.round((r.base + r.vat) * 100) / 100).toBeCloseTo(r.total, 2);
    }
  });
});

describe('calcVAT — property test (1,000+ generated cases, DB-free)', () => {
  // Small seeded PRNG (mulberry32) — deterministic across runs, no new
  // dependency needed for "100+ generated cases per property" per this
  // repo's established (PHP-side) property-testing convention.
  function mulberry32(seed: number): () => number {
    let a = seed;
    return () => {
      a |= 0;
      a = (a + 0x6d2b79f5) | 0;
      let t = Math.imul(a ^ (a >>> 15), 1 | a);
      t = (t + Math.imul(t ^ (t >>> 7), 61 | t)) ^ t;
      return ((t ^ (t >>> 14)) >>> 0) / 4294967296;
    };
  }

  const rand = mulberry32(20260524);
  const N = 1200;

  it('exclusive path: vat === round(subtotal*rate/100, 2), total === round(subtotal+vat_raw, 2), base === subtotal', () => {
    for (let i = 0; i < N; i++) {
      const subtotal = Math.round(rand() * 10_000_000) / 100;
      const rate = Math.round(rand() * 3000) / 100;
      const r = calcVAT(subtotal, rate, false);
      expect(r.base).toBe(subtotal);
      expect(r.total).toBeGreaterThanOrEqual(r.base);
      expect(r.vat).toBeGreaterThanOrEqual(0);
      // total == base + vat to the satang (both already rounded independently, same as PHP).
      expect(Math.abs(r.total - (r.base + r.vat))).toBeLessThanOrEqual(0.01);
    }
  });

  it('inclusive path: base <= total, vat >= 0, base+vat re-approximates total to the satang', () => {
    for (let i = 0; i < N; i++) {
      const subtotal = Math.round(rand() * 10_000_000) / 100;
      const rate = Math.round(rand() * 3000) / 100;
      const r = calcVAT(subtotal, rate, true);
      expect(r.total).toBe(subtotal);
      expect(r.base).toBeLessThanOrEqual(r.total);
      expect(r.vat).toBeGreaterThanOrEqual(0);
      expect(Math.abs(r.total - (r.base + r.vat))).toBeLessThanOrEqual(0.01);
    }
  });

  it('every result is an exact 2-decimal-place value (no residual float noise)', () => {
    for (let i = 0; i < N; i++) {
      const subtotal = Math.round(rand() * 10_000_000) / 137; // odd divisor -> messy decimals
      const rate = Math.round(rand() * 2500) / 100;
      const inclusive = rand() > 0.5;
      const r = calcVAT(subtotal, rate, inclusive);
      for (const v of [r.base, r.vat, r.total]) {
        expect(Math.round(v * 100)).toBeCloseTo(v * 100, 6);
      }
    }
  });
});

describe('computeLineTotal — golden fixture parity + property test', () => {
  it('fixture has 1,000+ cases and matches real PHP exactly', () => {
    expect(lineTotalCases.length).toBeGreaterThanOrEqual(1000);
    const mismatches: unknown[] = [];
    for (const c of lineTotalCases) {
      const got = computeLineTotal(c.qty, c.unit, c.discPct, c.discAmt);
      if (got !== c.expected) mismatches.push({ input: c, got });
    }
    expect(mismatches).toEqual([]);
  });

  it('floors at 0 when discount exceeds gross (never negative)', () => {
    expect(computeLineTotal(1, 10, 0, 1000)).toBe(0);
    expect(computeLineTotal(2, 5, 200, 0)).toBe(0); // 200% discount -> negative gross -> floored
  });

  it('discount_percent=0 leaves gross untouched by the percent branch (PHP only applies when > 0)', () => {
    expect(computeLineTotal(3, 10, 0, 0)).toBe(30);
  });
});

describe('formatMoney — golden fixture parity', () => {
  it('matches real PHP number_format($v, 2, ".", ",") output exactly', () => {
    expect(moneyCases.length).toBeGreaterThan(500);
    const mismatches: unknown[] = [];
    for (const c of moneyCases) {
      const got = formatMoney(c.v);
      if (got !== c.expected) mismatches.push({ input: c, got });
    }
    expect(mismatches).toEqual([]);
  });

  it('groups thousands with commas and always shows 2 decimals', () => {
    expect(formatMoney(1234567.5)).toBe('1,234,567.50');
    expect(formatMoney(0)).toBe('0.00');
    expect(formatMoney(-1500)).toBe('-1,500.00');
  });
});
