import { afterEach, beforeEach, describe, expect, it, vi } from 'vitest';
import {
  broadcastMessage,
  multicastMessage,
  pushMessage,
  replyMessage,
  sendMessage,
  validateSignature,
  type LineApiOptions,
  type LineFetch,
  type LineHttpRequestInit,
} from '../src/api';

// -------------------------------------------------------------------------------------------
// PHP cross-check fixtures — classes/LineAPI.php:959-963 `validateSignature()`
//
// Every (body, secret, expectedSignature) triple below was generated by shelling out to the
// REAL PHP class in this container (PHP 8.4.19 CLI):
//   $line = new LineAPI('unused-access-token', $secret);
//   $expected = base64_encode(hash_hmac('sha256', $body, $secret, true));
//   assert($line->validateSignature($body, $expected) === true);
//   assert($line->validateSignature($body, $tamperedSignature) === false);
//   assert($line->validateSignature($body . 'X', $expected) === false);
// All 23 fixtures round-tripped through those three assertions against the actual LineAPI class
// with zero failures before being copied in here — this is not a hand-computed table.
// -------------------------------------------------------------------------------------------

interface SignatureFixture {
  label: string;
  body: string;
  secret: string;
  expectedSignature: string;
}

const PHP_CROSS_CHECKED_SIGNATURES: SignatureFixture[] = [
  {
    label: 'typical webhook text message event',
    body: '{"destination":"U1234567890abcdef1234567890abcdef","events":[{"type":"message","message":{"type":"text","id":"1234567890","text":"สวัสดีครับ"},"timestamp":1720000000000,"source":{"type":"user","userId":"U0123456789abcdef0123456789abcdef"},"replyToken":"replytoken1234567890abcdef1234567890ab","mode":"active"}]}',
    secret: 'a1b2c3d4e5f6a7b8c9d0e1f2a3b4c5d6',
    expectedSignature: 'LpRc/Ol4pOe/0aMK7l9SIQ+L9UG5ch7FF3qanIomFuc=',
  },
  {
    label: 'empty body',
    body: '',
    secret: 'a1b2c3d4e5f6a7b8c9d0e1f2a3b4c5d6',
    expectedSignature: 'Vu75f5BMK13PfpsqE9RSMu84w/b/qfIWrKJckn08RGg=',
  },
  {
    label: 'simple ascii',
    body: 'hello world',
    secret: 'mysecret',
    expectedSignature: 'Xcn40IBvUoM37BfPopnMrItbXu326KiSaqvszAIzhw0=',
  },
  {
    label: 'thai text body',
    body: '{"text":"ร้านขายยาเปิดทำการ 08:00-20:00 น. ทุกวัน"}',
    secret: 'ไทยลับ1234',
    expectedSignature: 'I0r42g+aSsP/RUNPS9TasCqh1romVVhlvMSO3LcY0RU=',
  },
  {
    label: 'body with newlines',
    body: 'line one\nline two\r\nline three',
    secret: 'secret-with-newline-body',
    expectedSignature: '2XiyQqIf73dDSrRqaixLm2iwwdiN8pPKdpKM7zAT354=',
  },
  {
    label: 'long repeated body',
    body: 'ข้อความยาว-long segment-'.repeat(40),
    secret: 'longbodysecretlongbodysecret1234',
    expectedSignature: 'jpSKvC3rCdMaFlOz6OGVstcbsr9nWK6Ou7IebhueQss=',
  },
  {
    label: 'special chars body',
    body: '{"text":"quote\\" backslash\\\\ tab\\t newline\\n emoji 😀🎉"}',
    secret: 'special-secret-!@#$%^&*()',
    expectedSignature: '1BWi/OXqqVuZQoU5qcZtaodNegPGKLLDgVYqewGoIK4=',
  },
  {
    label: 'numeric secret',
    body: '{"a":1}',
    secret: '00000000000000000000000000000000',
    expectedSignature: 'X+1VtviRuCkEi9eg0d66Gv3ICIACCHWFZ/tu3Q4Plns=',
  },
  {
    label: 'single char body',
    body: 'x',
    secret: 'y',
    expectedSignature: 'olwjKkBPyKzZieMMsoyddk7gGaYt1lKhTeWk/smqrZo=',
  },
  {
    label: 'whitespace body',
    body: '   ',
    secret: 'whitespace-secret',
    expectedSignature: 'Z/RAPmrpXuGztP88MwDRquVv71iN2SBbAbo9PORvBN8=',
  },
  {
    label: 'body with escaped null',
    body: '{"x":"a\\u0000b"}',
    secret: 'null-secret',
    expectedSignature: 'h4Hpki7Q9KWqMMXHegmw9xb5YdBh3/ypIXpKOMoT33I=',
  },
  {
    label: 'very long secret',
    body: '{"ping":"pong"}',
    secret: 'secretpart-'.repeat(10),
    expectedSignature: 'L68wg3dOYJFj0zSzrvKNWUFM1DkfL5dhsDt/Mecb1ik=',
  },
  {
    label: 'same body diff secret A',
    body: '{"same":"body"}',
    secret: 'secretA',
    expectedSignature: 'FesB64zbCDdbNDmnugzpYJlj+ENoT0iOjRxXYSxSeyU=',
  },
  {
    label: 'same body diff secret B',
    body: '{"same":"body"}',
    secret: 'secretB',
    expectedSignature: 'QtzExLnyMmum8JgrYpDlyNQXVseqLO6/Xctv9cQhB5o=',
  },
  {
    label: 'postback event',
    body: '{"destination":"Udest","events":[{"type":"postback","postback":{"data":"action=buy&itemid=123"},"timestamp":1720000001000,"source":{"type":"user","userId":"U1111111111111111111111111111111"},"replyToken":"rt-postback-abcdefghijklmnopqrstuv","mode":"active"}]}',
    secret: 'postback-secret-9876543210',
    expectedSignature: 'hOPdUDdHJJDhGTcgt9uUycQG2yELsh8YJcZvO4h4VR8=',
  },
  {
    label: 'follow event',
    body: '{"destination":"Udest","events":[{"type":"follow","timestamp":1720000002000,"source":{"type":"user","userId":"U2222222222222222222222222222222"},"replyToken":"rt-follow-abcdefghijklmnopqrstuvwx","mode":"active"}]}',
    secret: 'follow-secret',
    expectedSignature: 'Omz71XukO/Z4n02EQh1SHJSrmldUUzQuAdc67WfVwfQ=',
  },
  {
    label: 'image message',
    body: '{"destination":"Udest","events":[{"type":"message","message":{"type":"image","id":"999888777","contentProvider":{"type":"line"}},"timestamp":1720000003000,"source":{"type":"user","userId":"U3333333333333333333333333333333"},"replyToken":"rt-image-abcdefghijklmnopqrstuvwxyz","mode":"active"}]}',
    secret: 'image-secret-!!',
    expectedSignature: 'r1aeHc0w6u91nOyxQJfBfPOTX0ViATffUATkH6nyVoY=',
  },
  {
    label: 'slash quote heavy',
    body: '{"path":"/uploads/2026/07/14/slip_abc123.jpg","note":"customer said \\"paid via transfer\\""}',
    secret: 'slash-quote-secret',
    expectedSignature: 'QQL324P0X0b2/WYcf9xE2yN++NkbdUgGYRx7Ly+Clf4=',
  },
  {
    label: 'form-encoded-looking value',
    body: '{"raw":"a=1&b=2&c=3"}',
    secret: 'amp-secret',
    expectedSignature: 'SXo3Q61B/cA+EMgT9icIAu2+LQvy3o063hMMrY+4P6Y=',
  },
  {
    label: 'minimal body',
    body: '{}',
    secret: 's',
    expectedSignature: 'FDyo1Re6GxgQJdcysc8nXZAQT8pXuwKlZVQpeKoYxLY=',
  },
  {
    label: 'secret with plus slash',
    body: '{"x":"y"}',
    secret: 'sec+ret/with=special',
    expectedSignature: 'BO4bSMJYYkuG/7HscNQorW+9g+kagoWpAy85vAWcKjo=',
  },
  {
    label: 'json tokens body',
    body: '{"a":null,"b":true,"c":false,"d":[1,2,3]}',
    secret: 'tokens-secret',
    expectedSignature: '7Vh8u4QnUipWQjlB/wJlm4ywtu+tyxKmmUQsSJtfE+g=',
  },
  {
    label: 'thai pharmacy order body',
    body: '{"order":"ยาพาราเซตามอล 500mg จำนวน 2 แผง, ราคา 25 บาท, ที่อยู่จัดส่ง: 123/45 ถ.สุขุมวิท กรุงเทพฯ 10110"}',
    secret: 'pharmacy-order-secret-th',
    expectedSignature: 'p5mHOWXZ+FPzP0kAeoQL5fHC0ujbMJzKVYDvdxZptS0=',
  },
];

describe('validateSignature — bit-for-bit port of classes/LineAPI.php:959-963', () => {
  it.each(PHP_CROSS_CHECKED_SIGNATURES)(
    'accepts the PHP-computed signature: $label',
    ({ body, secret, expectedSignature }) => {
      expect(validateSignature(body, expectedSignature, secret)).toBe(true);
    }
  );

  it.each(PHP_CROSS_CHECKED_SIGNATURES)(
    'rejects a tampered signature (last char flipped): $label',
    ({ body, secret, expectedSignature }) => {
      const lastChar = expectedSignature.slice(-1);
      const tampered = expectedSignature.slice(0, -1) + (lastChar === 'A' ? 'B' : 'A');
      expect(validateSignature(body, tampered, secret)).toBe(false);
    }
  );

  it.each(PHP_CROSS_CHECKED_SIGNATURES)(
    'rejects a tampered body: $label',
    ({ body, secret, expectedSignature }) => {
      expect(validateSignature(`${body}X`, expectedSignature, secret)).toBe(false);
    }
  );

  it.each(PHP_CROSS_CHECKED_SIGNATURES)(
    'rejects the wrong channel secret: $label',
    ({ body, expectedSignature }) => {
      expect(validateSignature(body, expectedSignature, 'definitely-the-wrong-secret')).toBe(false);
    }
  );

  it('rejects an empty signature without throwing', () => {
    const fixture = PHP_CROSS_CHECKED_SIGNATURES[0]!;
    expect(() => validateSignature(fixture.body, '', fixture.secret)).not.toThrow();
    expect(validateSignature(fixture.body, '', fixture.secret)).toBe(false);
  });

  it('rejects non-base64 garbage signatures without throwing', () => {
    const fixture = PHP_CROSS_CHECKED_SIGNATURES[0]!;
    const garbageInputs = [
      'not-base64-at-all!!!',
      '<<<>>>???',
      ' control-bytes',
      'ก ข ค ง แ ไทย ไม่ใช่ base64',
      '   ',
      'null',
    ];
    for (const garbage of garbageInputs) {
      expect(() => validateSignature(fixture.body, garbage, fixture.secret)).not.toThrow();
      expect(validateSignature(fixture.body, garbage, fixture.secret)).toBe(false);
    }
  });

  it('rejects length-mismatched signatures without throwing — the naive crypto.timingSafeEqual bug this must not have', () => {
    const fixture = PHP_CROSS_CHECKED_SIGNATURES[0]!;
    // A direct `crypto.timingSafeEqual(Buffer.from(expected), Buffer.from(signature))` port would
    // throw `RangeError: Input buffers must have the same byte length` for every input below.
    const lengthMismatchedSignatures = [
      'a',
      'ab',
      fixture.expectedSignature.slice(0, 10),
      fixture.expectedSignature.slice(0, 43), // one byte short of the real 44-char base64 output
      `${fixture.expectedSignature}extra`,
      `${fixture.expectedSignature}=`, // one byte over
      'x'.repeat(1000),
    ];
    for (const signature of lengthMismatchedSignatures) {
      expect(() => validateSignature(fixture.body, signature, fixture.secret)).not.toThrow();
      expect(validateSignature(fixture.body, signature, fixture.secret)).toBe(false);
    }
  });

  it('accepts a Buffer body identically to the equivalent UTF-8 string body', () => {
    const fixture = PHP_CROSS_CHECKED_SIGNATURES[0]!;
    expect(
      validateSignature(Buffer.from(fixture.body, 'utf8'), fixture.expectedSignature, fixture.secret)
    ).toBe(true);
  });

  it('a Thai-text body signs identically whether passed as a string or its UTF-8 Buffer', () => {
    const fixture = PHP_CROSS_CHECKED_SIGNATURES.find((f) => f.label === 'thai text body')!;
    expect(
      validateSignature(Buffer.from(fixture.body, 'utf8'), fixture.expectedSignature, fixture.secret)
    ).toBe(true);
  });
});

// -------------------------------------------------------------------------------------------
// sendMessage() ordering — classes/LineAPI.php:121-161
// -------------------------------------------------------------------------------------------

/** Records every call made through the injected transport; never touches a real socket. */
function createFetchMock(responses: Array<{ status: number; body: unknown }>): {
  fetchImpl: LineFetch;
  calls: Array<{ url: string; init: LineHttpRequestInit }>;
} {
  const calls: Array<{ url: string; init: LineHttpRequestInit }> = [];
  let callIndex = 0;
  const fetchImpl: LineFetch = async (url, init) => {
    calls.push({ url, init });
    const response = responses[Math.min(callIndex, responses.length - 1)];
    callIndex += 1;
    if (!response) {
      throw new Error('createFetchMock: no response configured for this call');
    }
    return {
      status: response.status,
      json: async () => response.body,
    };
  };
  return { fetchImpl, calls };
}

/** Formats a Date as a bare "YYYY-MM-DD HH:MM:SS" Asia/Bangkok wall-clock string — the same
 * shape `users.reply_token_expires` (a MySQL DATETIME, no offset) actually has in the DB. */
function toBangkokDatetimeString(date: Date): string {
  const parts = new Intl.DateTimeFormat('en-CA', {
    timeZone: 'Asia/Bangkok',
    year: 'numeric',
    month: '2-digit',
    day: '2-digit',
    hour: '2-digit',
    minute: '2-digit',
    second: '2-digit',
    hour12: false,
  }).formatToParts(date);
  const get = (type: string): string => parts.find((p) => p.type === type)?.value ?? '00';
  return `${get('year')}-${get('month')}-${get('day')} ${get('hour')}:${get('minute')}:${get('second')}`;
}

function futureBangkokDatetime(msFromNow: number): string {
  return toBangkokDatetimeString(new Date(Date.now() + msFromNow));
}

function pastBangkokDatetime(msAgo: number): string {
  return toBangkokDatetimeString(new Date(Date.now() - msAgo));
}

const BASE_OPTIONS: Omit<LineApiOptions, 'fetchImpl'> = { channelAccessToken: 'test-channel-access-token' };

describe('sendMessage — reply-token-first / push-fallback dispatcher', () => {
  // Safety net: if the implementation ever bypasses the injected fetchImpl mock and falls
  // through to the real transport (defaultFetch -> global fetch), this guard throws instead of
  // silently letting a real network call happen — every test in this block fails loudly if the
  // mock is bypassed, per the acceptance criteria.
  let guardHits: number;
  beforeEach(() => {
    guardHits = 0;
    vi.stubGlobal('fetch', async () => {
      guardHits += 1;
      throw new Error(
        '[test guard] global fetch was invoked directly — every LINE API call must go through the injected fetchImpl mock, not the real transport'
      );
    });
  });
  afterEach(() => {
    vi.unstubAllGlobals();
  });

  it('reply-success (HTTP 200) never calls push', async () => {
    const { fetchImpl, calls } = createFetchMock([{ status: 200, body: { sentMessages: [{ id: '1' }] } }]);
    const onReplyTokenUsed = vi.fn();

    const result = await sendMessage(
      {
        userId: 'Uabc123',
        messages: 'สวัสดีครับ',
        replyToken: 'reply-token-live',
        tokenExpires: futureBangkokDatetime(5 * 60_000),
        internalUserId: 42,
        onReplyTokenUsed,
      },
      { ...BASE_OPTIONS, fetchImpl }
    );

    expect(calls).toHaveLength(1);
    expect(calls[0]!.url).toBe('https://api.line.me/v2/bot/message/reply');
    expect(result).toEqual({ code: 200, body: { sentMessages: [{ id: '1' }] }, method: 'reply' });
    expect(guardHits).toBe(0);
  });

  it('reply-fail (non-200) falls back to push, called strictly after reply', async () => {
    const { fetchImpl, calls } = createFetchMock([
      { status: 400, body: { message: 'Invalid reply token' } },
      { status: 200, body: { sentMessages: [{ id: '2' }] } },
    ]);

    const result = await sendMessage(
      {
        userId: 'Uabc123',
        messages: 'hi',
        replyToken: 'reply-token-live',
        tokenExpires: futureBangkokDatetime(5 * 60_000),
      },
      { ...BASE_OPTIONS, fetchImpl }
    );

    expect(calls).toHaveLength(2);
    expect(calls[0]!.url).toBe('https://api.line.me/v2/bot/message/reply');
    expect(calls[1]!.url).toBe('https://api.line.me/v2/bot/message/push');
    expect(result).toEqual({ code: 200, body: { sentMessages: [{ id: '2' }] }, method: 'push' });
    expect(guardHits).toBe(0);
  });

  it('expired token calls push only — reply is never attempted', async () => {
    const { fetchImpl, calls } = createFetchMock([{ status: 200, body: { sentMessages: [] } }]);

    const result = await sendMessage(
      {
        userId: 'Uabc123',
        messages: 'hi',
        replyToken: 'reply-token-expired',
        tokenExpires: pastBangkokDatetime(60_000),
      },
      { ...BASE_OPTIONS, fetchImpl }
    );

    expect(calls).toHaveLength(1);
    expect(calls[0]!.url).toBe('https://api.line.me/v2/bot/message/push');
    expect(result.method).toBe('push');
    expect(guardHits).toBe(0);
  });

  it.each([undefined, null, ''] as const)('no reply token (%s) sends push directly', async (replyToken) => {
    const { fetchImpl, calls } = createFetchMock([{ status: 200, body: {} }]);

    const result = await sendMessage(
      { userId: 'Uabc123', messages: 'hi', replyToken },
      { ...BASE_OPTIONS, fetchImpl }
    );

    expect(calls).toHaveLength(1);
    expect(calls[0]!.url).toBe('https://api.line.me/v2/bot/message/push');
    expect(result.method).toBe('push');
    expect(guardHits).toBe(0);
  });

  it('a token with no recorded expiry is treated as valid (reply is attempted)', async () => {
    const { fetchImpl, calls } = createFetchMock([{ status: 200, body: {} }]);

    const result = await sendMessage(
      { userId: 'Uabc123', messages: 'hi', replyToken: 'reply-token-no-expiry', tokenExpires: null },
      { ...BASE_OPTIONS, fetchImpl }
    );

    expect(calls[0]!.url).toBe('https://api.line.me/v2/bot/message/reply');
    expect(result.method).toBe('reply');
  });

  describe('single-use token-clear callback — invoked exactly once, regardless of which reply-token branch is taken', () => {
    it.each([
      {
        branch: 'reply success',
        tokenExpires: () => futureBangkokDatetime(5 * 60_000),
        responses: [{ status: 200, body: {} }],
        expectedTransportCalls: 1,
      },
      {
        branch: 'reply failure (non-200)',
        tokenExpires: () => futureBangkokDatetime(5 * 60_000),
        responses: [
          { status: 500, body: {} },
          { status: 200, body: {} },
        ],
        expectedTransportCalls: 2,
      },
      {
        branch: 'expired token',
        tokenExpires: () => pastBangkokDatetime(60_000),
        responses: [{ status: 200, body: {} }],
        expectedTransportCalls: 1,
      },
    ])('$branch: onReplyTokenUsed called exactly once', async ({ tokenExpires, responses, expectedTransportCalls }) => {
      const { fetchImpl, calls } = createFetchMock(responses);
      const onReplyTokenUsed = vi.fn();

      await sendMessage(
        {
          userId: 'Uxyz789',
          messages: 'hi',
          replyToken: 'reply-token-under-test',
          tokenExpires: tokenExpires(),
          internalUserId: 7,
          onReplyTokenUsed,
        },
        { ...BASE_OPTIONS, fetchImpl }
      );

      expect(onReplyTokenUsed).toHaveBeenCalledTimes(1);
      expect(onReplyTokenUsed).toHaveBeenCalledWith({ lineUserId: 'Uxyz789', internalUserId: 7 });
      expect(calls).toHaveLength(expectedTransportCalls);
    });

    it('no reply token supplied: onReplyTokenUsed is never invoked (nothing to clear)', async () => {
      const { fetchImpl } = createFetchMock([{ status: 200, body: {} }]);
      const onReplyTokenUsed = vi.fn();

      await sendMessage(
        { userId: 'Uxyz789', messages: 'hi', replyToken: null, onReplyTokenUsed },
        { ...BASE_OPTIONS, fetchImpl }
      );

      expect(onReplyTokenUsed).not.toHaveBeenCalled();
    });

    it('omitting onReplyTokenUsed entirely does not throw, for every reply-token branch', async () => {
      const expired = createFetchMock([{ status: 200, body: {} }]);
      await expect(
        sendMessage(
          { userId: 'U1', messages: 'hi', replyToken: 'rt', tokenExpires: pastBangkokDatetime(1000) },
          { ...BASE_OPTIONS, fetchImpl: expired.fetchImpl }
        )
      ).resolves.toBeDefined();

      const success = createFetchMock([{ status: 200, body: {} }]);
      await expect(
        sendMessage(
          { userId: 'U1', messages: 'hi', replyToken: 'rt', tokenExpires: futureBangkokDatetime(60_000) },
          { ...BASE_OPTIONS, fetchImpl: success.fetchImpl }
        )
      ).resolves.toBeDefined();
    });
  });

  describe('message normalization (matches sendMessage()\'s $messages branching in classes/LineAPI.php:121-129)', () => {
    it('wraps a bare string into a single text message', async () => {
      const { fetchImpl, calls } = createFetchMock([{ status: 200, body: {} }]);
      await sendMessage({ userId: 'U1', messages: 'hello there' }, { ...BASE_OPTIONS, fetchImpl });
      const payload = JSON.parse(calls[0]!.init.body) as { to: string; messages: unknown };
      expect(payload.messages).toEqual([{ type: 'text', text: 'hello there' }]);
    });

    it('wraps a single message object (has "type") into a one-element array', async () => {
      const { fetchImpl, calls } = createFetchMock([{ status: 200, body: {} }]);
      const flexMessage = { type: 'flex', altText: 'label', contents: { type: 'bubble' } };
      await sendMessage({ userId: 'U1', messages: flexMessage }, { ...BASE_OPTIONS, fetchImpl });
      const payload = JSON.parse(calls[0]!.init.body) as { messages: unknown };
      expect(payload.messages).toEqual([flexMessage]);
    });

    it('passes an already-array list of messages through unchanged', async () => {
      const { fetchImpl, calls } = createFetchMock([{ status: 200, body: {} }]);
      const messages = [
        { type: 'text', text: 'one' },
        { type: 'text', text: 'two' },
      ];
      await sendMessage({ userId: 'U1', messages }, { ...BASE_OPTIONS, fetchImpl });
      const payload = JSON.parse(calls[0]!.init.body) as { messages: unknown };
      expect(payload.messages).toEqual(messages);
    });
  });
});

describe('replyMessage / pushMessage — classes/LineAPI.php:80-108', () => {
  it('replyMessage POSTs { replyToken, messages } to /message/reply with a Bearer auth header', async () => {
    const { fetchImpl, calls } = createFetchMock([{ status: 200, body: { sentMessages: [] } }]);
    const result = await replyMessage('rt-1', 'hi', { channelAccessToken: 'secret-token-value', fetchImpl });

    expect(calls).toHaveLength(1);
    expect(calls[0]!.url).toBe('https://api.line.me/v2/bot/message/reply');
    expect(calls[0]!.init.method).toBe('POST');
    expect(calls[0]!.init.headers).toMatchObject({
      'Content-Type': 'application/json',
      Authorization: 'Bearer secret-token-value',
    });
    expect(JSON.parse(calls[0]!.init.body)).toEqual({
      replyToken: 'rt-1',
      messages: [{ type: 'text', text: 'hi' }],
    });
    expect(result).toEqual({ code: 200, body: { sentMessages: [] } });
  });

  it('pushMessage POSTs { to, messages } to /message/push', async () => {
    const { fetchImpl, calls } = createFetchMock([{ status: 200, body: { sentMessages: [] } }]);
    const result = await pushMessage('U-target', ['already', 'an-array-placeholder'].map((t) => ({ type: 'text', text: t })), {
      channelAccessToken: 'tok',
      fetchImpl,
    });

    expect(calls[0]!.url).toBe('https://api.line.me/v2/bot/message/push');
    expect(JSON.parse(calls[0]!.init.body)).toEqual({
      to: 'U-target',
      messages: [
        { type: 'text', text: 'already' },
        { type: 'text', text: 'an-array-placeholder' },
      ],
    });
    expect(result.code).toBe(200);
  });

  it('respects an apiEndpoint override for both reply and push', async () => {
    const { fetchImpl, calls } = createFetchMock([
      { status: 200, body: {} },
      { status: 200, body: {} },
    ]);
    await replyMessage('rt', 'hi', { channelAccessToken: 'tok', apiEndpoint: 'https://example.test/bot', fetchImpl });
    await pushMessage('U1', 'hi', { channelAccessToken: 'tok', apiEndpoint: 'https://example.test/bot', fetchImpl });

    expect(calls[0]!.url).toBe('https://example.test/bot/message/reply');
    expect(calls[1]!.url).toBe('https://example.test/bot/message/push');
  });

  it('resolves with a null body (not a throw) when the response is not valid JSON', async () => {
    const fetchImpl: LineFetch = async () => ({
      status: 200,
      json: async () => {
        throw new SyntaxError('Unexpected end of JSON input');
      },
    });
    const result = await pushMessage('U1', 'hi', { channelAccessToken: 'tok', fetchImpl });
    expect(result).toEqual({ code: 200, body: null });
  });

  describe('a single message object passed directly is NOT array-wrapped (PHP is_array() pass-through)', () => {
    // classes/LineAPI.php:82-84 / 99-101: `if (!is_array($messages)) { wrap }` — a PHP
    // associative array (a single message hash) is already `is_array() === true`, so it is
    // passed straight through and json_encode()'s "messages" field is a JSON *object*, not a
    // one-element array. This is the exact call shape webhook.php:2051 uses today:
    //   $line->replyMessage($replyToken, ['type' => 'text', 'text' => '...']);
    // Only sendMessage() (classes/LineAPI.php:126-128, `isset($messages['type'])`) wraps a lone
    // object into a one-element array before ever calling replyMessage()/pushMessage() — see the
    // 'wraps a single message object ... into a one-element array' case in the sendMessage()
    // describe block above, which covers that (deliberately different) behavior.
    it('replyMessage: a single message object is sent unwrapped, matching webhook.php:2051', async () => {
      const { fetchImpl, calls } = createFetchMock([{ status: 200, body: {} }]);
      const singleMessage = { type: 'text', text: 'สวัสดีครับ' };
      await replyMessage('rt-1', singleMessage, { channelAccessToken: 'tok', fetchImpl });

      const payload = JSON.parse(calls[0]!.init.body) as { messages: unknown };
      expect(payload.messages).toEqual(singleMessage);
      expect(Array.isArray(payload.messages)).toBe(false);
    });

    it('pushMessage: a single message object is sent unwrapped', async () => {
      const { fetchImpl, calls } = createFetchMock([{ status: 200, body: {} }]);
      const singleMessage = { type: 'flex', altText: 'label', contents: { type: 'bubble' } };
      await pushMessage('U1', singleMessage, { channelAccessToken: 'tok', fetchImpl });

      const payload = JSON.parse(calls[0]!.init.body) as { messages: unknown };
      expect(payload.messages).toEqual(singleMessage);
      expect(Array.isArray(payload.messages)).toBe(false);
    });

    it('a bare string is still wrapped into a one-element text array (the one case PHP does wrap)', async () => {
      const { fetchImpl, calls } = createFetchMock([{ status: 200, body: {} }]);
      await replyMessage('rt-1', 'plain string', { channelAccessToken: 'tok', fetchImpl });

      const payload = JSON.parse(calls[0]!.init.body) as { messages: unknown };
      expect(payload.messages).toEqual([{ type: 'text', text: 'plain string' }]);
    });
  });
});

describe('multicastMessage / broadcastMessage — classes/LineAPI.php:219-241', () => {
  it('multicastMessage POSTs { to, messages } to /message/multicast with a Bearer auth header', async () => {
    const { fetchImpl, calls } = createFetchMock([{ status: 200, body: { sentMessages: [] } }]);
    const userIds = ['U1', 'U2', 'U3'];
    const result = await multicastMessage(userIds, 'hi everyone', { channelAccessToken: 'secret-token-value', fetchImpl });

    expect(calls).toHaveLength(1);
    expect(calls[0]!.url).toBe('https://api.line.me/v2/bot/message/multicast');
    expect(calls[0]!.init.method).toBe('POST');
    expect(calls[0]!.init.headers).toMatchObject({
      'Content-Type': 'application/json',
      Authorization: 'Bearer secret-token-value',
    });
    expect(JSON.parse(calls[0]!.init.body)).toEqual({
      to: userIds,
      messages: [{ type: 'text', text: 'hi everyone' }],
    });
    expect(result).toEqual({ code: 200, body: { sentMessages: [] } });
  });

  it('multicastMessage passes an array of message objects through unchanged', async () => {
    const { fetchImpl, calls } = createFetchMock([{ status: 200, body: {} }]);
    const messages = [
      { type: 'text', text: 'one' },
      { type: 'text', text: 'two' },
    ];
    await multicastMessage(['U1'], messages, { channelAccessToken: 'tok', fetchImpl });
    const payload = JSON.parse(calls[0]!.init.body) as { messages: unknown };
    expect(payload.messages).toEqual(messages);
  });

  it('multicastMessage sends a single message object unwrapped (PHP is_array() pass-through, matching pushMessage/replyMessage)', async () => {
    const { fetchImpl, calls } = createFetchMock([{ status: 200, body: {} }]);
    const singleMessage = { type: 'flex', altText: 'label', contents: { type: 'bubble' } };
    await multicastMessage(['U1', 'U2'], singleMessage, { channelAccessToken: 'tok', fetchImpl });
    const payload = JSON.parse(calls[0]!.init.body) as { messages: unknown; to: string[] };
    expect(payload.messages).toEqual(singleMessage);
    expect(Array.isArray(payload.messages)).toBe(false);
    expect(payload.to).toEqual(['U1', 'U2']);
  });

  it('multicastMessage propagates a non-200 LINE response code without throwing (caller decides sentCount accounting)', async () => {
    const { fetchImpl } = createFetchMock([{ status: 429, body: { message: 'rate limited' } }]);
    const result = await multicastMessage(['U1'], 'hi', { channelAccessToken: 'tok', fetchImpl });
    expect(result).toEqual({ code: 429, body: { message: 'rate limited' } });
  });

  it('broadcastMessage POSTs { messages } (no "to" field) to /message/broadcast', async () => {
    const { fetchImpl, calls } = createFetchMock([{ status: 200, body: { sentMessages: [] } }]);
    const result = await broadcastMessage('hello everyone', { channelAccessToken: 'secret-token-value', fetchImpl });

    expect(calls).toHaveLength(1);
    expect(calls[0]!.url).toBe('https://api.line.me/v2/bot/message/broadcast');
    expect(calls[0]!.init.method).toBe('POST');
    const payload = JSON.parse(calls[0]!.init.body) as Record<string, unknown>;
    expect(payload).toEqual({ messages: [{ type: 'text', text: 'hello everyone' }] });
    expect('to' in payload).toBe(false);
    expect(result).toEqual({ code: 200, body: { sentMessages: [] } });
  });

  it('broadcastMessage sends a single message object unwrapped, an array of messages unchanged, and respects apiEndpoint override', async () => {
    const { fetchImpl, calls } = createFetchMock([
      { status: 200, body: {} },
      { status: 200, body: {} },
      { status: 200, body: {} },
    ]);
    const singleMessage = { type: 'image', originalContentUrl: 'https://x/img.jpg', previewImageUrl: 'https://x/img.jpg' };
    await broadcastMessage(singleMessage, { channelAccessToken: 'tok', fetchImpl });
    const arrayMessages = [{ type: 'text', text: 'a' }, { type: 'text', text: 'b' }];
    await broadcastMessage(arrayMessages, { channelAccessToken: 'tok', fetchImpl });
    await broadcastMessage('hi', { channelAccessToken: 'tok', apiEndpoint: 'https://example.test/bot', fetchImpl });

    expect(JSON.parse(calls[0]!.init.body)).toEqual({ messages: singleMessage });
    expect(Array.isArray((JSON.parse(calls[0]!.init.body) as { messages: unknown }).messages)).toBe(false);
    expect(JSON.parse(calls[1]!.init.body)).toEqual({ messages: arrayMessages });
    expect(calls[2]!.url).toBe('https://example.test/bot/message/broadcast');
  });

  it('resolves with a null body (not a throw) when the response is not valid JSON, for both multicastMessage and broadcastMessage', async () => {
    const notJsonFetch: LineFetch = async () => ({
      status: 200,
      json: async () => {
        throw new SyntaxError('Unexpected end of JSON input');
      },
    });
    expect(await multicastMessage(['U1'], 'hi', { channelAccessToken: 'tok', fetchImpl: notJsonFetch })).toEqual({
      code: 200,
      body: null,
    });
    expect(await broadcastMessage('hi', { channelAccessToken: 'tok', fetchImpl: notJsonFetch })).toEqual({
      code: 200,
      body: null,
    });
  });

  it('delegates to the runtime global fetch when fetchImpl is omitted for both functions (real transport, not stubbed)', async () => {
    const globalFetchMock = vi.fn(async (_url: string, _init: unknown) => ({
      status: 200,
      json: async () => ({ sentMessages: [] }),
    }));
    vi.stubGlobal('fetch', globalFetchMock);
    try {
      await multicastMessage(['U1'], 'hi', { channelAccessToken: 'token-abc' });
      await broadcastMessage('hi', { channelAccessToken: 'token-abc' });
      expect(globalFetchMock).toHaveBeenCalledTimes(2);
      expect(globalFetchMock.mock.calls[0]?.[0]).toBe('https://api.line.me/v2/bot/message/multicast');
      expect(globalFetchMock.mock.calls[1]?.[0]).toBe('https://api.line.me/v2/bot/message/broadcast');
    } finally {
      vi.unstubAllGlobals();
    }
  });
});

describe('default transport wiring — no fetchImpl override supplied', () => {
  afterEach(() => {
    vi.unstubAllGlobals();
  });

  it('delegates to the runtime global fetch when fetchImpl is omitted (the real transport is implemented, not stubbed out)', async () => {
    const globalFetchMock = vi.fn(async (_url: string, _init: unknown) => ({
      status: 200,
      json: async () => ({ sentMessages: [] }),
    }));
    vi.stubGlobal('fetch', globalFetchMock);

    const result = await replyMessage('reply-token-xyz', 'hello', { channelAccessToken: 'token-abc' });

    expect(globalFetchMock).toHaveBeenCalledTimes(1);
    expect(globalFetchMock.mock.calls[0]?.[0]).toBe('https://api.line.me/v2/bot/message/reply');
    expect(result).toEqual({ code: 200, body: { sentMessages: [] } });
  });

  it('throws a clear, actionable error instead of crashing cryptically when no fetch exists at all', async () => {
    vi.stubGlobal('fetch', undefined);
    await expect(replyMessage('rt', 'hi', { channelAccessToken: 'token-abc' })).rejects.toThrow(
      /global fetch is unavailable/
    );
  });
});
