-- ---------------------------------------------------------------------------
-- Migration: 2026-05-15 restore PRIMARY KEY + AUTO_INCREMENT on 280 tables
-- ---------------------------------------------------------------------------
-- Production audit on 2026-05-15 found that the `zrismpsz_demo` database
-- had been imported WITHOUT primary keys, AUTO_INCREMENT, or secondary
-- indexes on the majority of its 303 tables. Only 14 tables had a
-- PRIMARY KEY at audit time. As a result, INSERTs into nearly every table
-- failed with SQLSTATE[HY000]: 1364 Field 'id' doesn't have a default value
-- under STRICT_TRANS_TABLES sql_mode.
--
-- This migration restores PRIMARY KEY (id) on every table that has an
-- `id` column NOT NULL but no PRIMARY KEY. For integer id columns we also
-- restore AUTO_INCREMENT. For varchar id columns (inbox_* UUID-keyed
-- tables) we add PRIMARY KEY only — AUTO_INCREMENT is invalid for varchar.
--
-- Three tables had existing data with bad ids and need a renumber pass
-- before the ALTER:
--   * business_categories — 12 rows all with id=0
--   * telegram_settings   — 2 rows with duplicate id
--   * admin_users         — 2 rows with unique ids (direct ALTER, no renumber)
--
-- Safe to re-run: if a PRIMARY KEY already exists the ALTER fails for that
-- table; use `mysql --force` so the rest still apply.
-- ---------------------------------------------------------------------------

SET time_zone = '+07:00';

-- =========================================================================
-- Section A: renumber bad ids on the 2 tables that have data with id=0 or
-- duplicate id. We use the user-variable trick so each row gets a fresh
-- sequential id starting at 1.
-- =========================================================================
SET @i := 0;
UPDATE `business_categories` SET `id` = (@i := @i + 1);

SET @i := 0;
UPDATE `telegram_settings`   SET `id` = (@i := @i + 1);

-- =========================================================================
-- Section B: ADD PRIMARY KEY + AUTO_INCREMENT on the 3 data-bearing tables.
-- =========================================================================
ALTER TABLE `business_categories` ADD PRIMARY KEY (`id`), MODIFY `id` int(11) NOT NULL AUTO_INCREMENT;
ALTER TABLE `telegram_settings`   ADD PRIMARY KEY (`id`), MODIFY `id` int(11) NOT NULL AUTO_INCREMENT;
ALTER TABLE `admin_users`         ADD PRIMARY KEY (`id`), MODIFY `id` int(11) NOT NULL AUTO_INCREMENT;

-- =========================================================================
-- Section C: ADD PRIMARY KEY (and AUTO_INCREMENT for integer ids) on the
-- remaining empty tables. Generated by scripts/generate_pk_migration.sql
-- against information_schema.COLUMNS + TABLE_CONSTRAINTS.
-- =========================================================================
ALTER TABLE `account_daily_stats` ADD PRIMARY KEY (`id`), MODIFY `id` int(11) NOT NULL AUTO_INCREMENT;
ALTER TABLE `account_events` ADD PRIMARY KEY (`id`), MODIFY `id` int(11) NOT NULL AUTO_INCREMENT;
ALTER TABLE `account_followers` ADD PRIMARY KEY (`id`), MODIFY `id` int(11) NOT NULL AUTO_INCREMENT;
ALTER TABLE `account_payables` ADD PRIMARY KEY (`id`), MODIFY `id` int(11) NOT NULL AUTO_INCREMENT;
ALTER TABLE `account_receivables` ADD PRIMARY KEY (`id`), MODIFY `id` int(11) NOT NULL AUTO_INCREMENT;
ALTER TABLE `admin_activity_log` ADD PRIMARY KEY (`id`), MODIFY `id` int(11) NOT NULL AUTO_INCREMENT;
ALTER TABLE `admin_bot_access` ADD PRIMARY KEY (`id`), MODIFY `id` int(11) NOT NULL AUTO_INCREMENT;
ALTER TABLE `admin_quick_access` ADD PRIMARY KEY (`id`), MODIFY `id` int(11) NOT NULL AUTO_INCREMENT;
ALTER TABLE `ai_chat_logs` ADD PRIMARY KEY (`id`), MODIFY `id` int(11) NOT NULL AUTO_INCREMENT;
ALTER TABLE `ai_chat_settings` ADD PRIMARY KEY (`id`), MODIFY `id` int(11) NOT NULL AUTO_INCREMENT;
ALTER TABLE `ai_conversations` ADD PRIMARY KEY (`id`), MODIFY `id` int(11) NOT NULL AUTO_INCREMENT;
ALTER TABLE `ai_conversation_history` ADD PRIMARY KEY (`id`), MODIFY `id` int(11) NOT NULL AUTO_INCREMENT;
ALTER TABLE `ai_pharmacy_settings` ADD PRIMARY KEY (`id`), MODIFY `id` int(11) NOT NULL AUTO_INCREMENT;
ALTER TABLE `ai_settings` ADD PRIMARY KEY (`id`), MODIFY `id` int(11) NOT NULL AUTO_INCREMENT;
ALTER TABLE `ai_triage_assessments` ADD PRIMARY KEY (`id`), MODIFY `id` int(11) NOT NULL AUTO_INCREMENT;
ALTER TABLE `ai_user_mode` ADD PRIMARY KEY (`id`), MODIFY `id` int(11) NOT NULL AUTO_INCREMENT;
ALTER TABLE `ai_user_pause` ADD PRIMARY KEY (`id`), MODIFY `id` int(11) NOT NULL AUTO_INCREMENT;
ALTER TABLE `analytics` ADD PRIMARY KEY (`id`), MODIFY `id` int(11) NOT NULL AUTO_INCREMENT;
ALTER TABLE `appointments` ADD PRIMARY KEY (`id`), MODIFY `id` int(11) NOT NULL AUTO_INCREMENT;
ALTER TABLE `auto_replies` ADD PRIMARY KEY (`id`), MODIFY `id` int(11) NOT NULL AUTO_INCREMENT;
ALTER TABLE `auto_reply_rules` ADD PRIMARY KEY (`id`), MODIFY `id` int(11) NOT NULL AUTO_INCREMENT;
ALTER TABLE `auto_tag_logs` ADD PRIMARY KEY (`id`), MODIFY `id` int(11) NOT NULL AUTO_INCREMENT;
ALTER TABLE `auto_tag_rules` ADD PRIMARY KEY (`id`), MODIFY `id` int(11) NOT NULL AUTO_INCREMENT;
ALTER TABLE `birthday_campaigns` ADD PRIMARY KEY (`id`), MODIFY `id` int(11) NOT NULL AUTO_INCREMENT;
ALTER TABLE `broadcasts` ADD PRIMARY KEY (`id`), MODIFY `id` int(11) NOT NULL AUTO_INCREMENT;
ALTER TABLE `broadcast_campaigns` ADD PRIMARY KEY (`id`), MODIFY `id` int(11) NOT NULL AUTO_INCREMENT;
ALTER TABLE `broadcast_clicks` ADD PRIMARY KEY (`id`), MODIFY `id` int(11) NOT NULL AUTO_INCREMENT;
ALTER TABLE `broadcast_items` ADD PRIMARY KEY (`id`), MODIFY `id` int(11) NOT NULL AUTO_INCREMENT;
ALTER TABLE `broadcast_messages` ADD PRIMARY KEY (`id`), MODIFY `id` int(11) NOT NULL AUTO_INCREMENT;
ALTER TABLE `broadcast_messages_v2` ADD PRIMARY KEY (`id`), MODIFY `id` int(11) NOT NULL AUTO_INCREMENT;
ALTER TABLE `broadcast_queue` ADD PRIMARY KEY (`id`), MODIFY `id` int(11) NOT NULL AUTO_INCREMENT;
ALTER TABLE `business_items` ADD PRIMARY KEY (`id`), MODIFY `id` int(11) NOT NULL AUTO_INCREMENT;
ALTER TABLE `business_settings` ADD PRIMARY KEY (`id`), MODIFY `id` int(11) NOT NULL AUTO_INCREMENT;
ALTER TABLE `cart` ADD PRIMARY KEY (`id`), MODIFY `id` int(11) NOT NULL AUTO_INCREMENT;
ALTER TABLE `cart_items` ADD PRIMARY KEY (`id`), MODIFY `id` int(11) NOT NULL AUTO_INCREMENT;
ALTER TABLE `cart_items_backup` ADD PRIMARY KEY (`id`), MODIFY `id` int(11) NOT NULL AUTO_INCREMENT;
ALTER TABLE `category_points_bonus` ADD PRIMARY KEY (`id`), MODIFY `id` int(11) NOT NULL AUTO_INCREMENT;
ALTER TABLE `chat_status_history` ADD PRIMARY KEY (`id`), MODIFY `id` int(11) NOT NULL AUTO_INCREMENT;
ALTER TABLE `cleanup_actions` ADD PRIMARY KEY (`id`), MODIFY `id` int(11) NOT NULL AUTO_INCREMENT;
ALTER TABLE `cleanup_backups` ADD PRIMARY KEY (`id`), MODIFY `id` int(11) NOT NULL AUTO_INCREMENT;
ALTER TABLE `cleanup_inventory` ADD PRIMARY KEY (`id`), MODIFY `id` int(11) NOT NULL AUTO_INCREMENT;
ALTER TABLE `cleanup_reports` ADD PRIMARY KEY (`id`), MODIFY `id` int(11) NOT NULL AUTO_INCREMENT;
ALTER TABLE `cny_products` ADD PRIMARY KEY (`id`), MODIFY `id` int(11) NOT NULL AUTO_INCREMENT;
ALTER TABLE `consent_logs` ADD PRIMARY KEY (`id`), MODIFY `id` int(11) NOT NULL AUTO_INCREMENT;
ALTER TABLE `consultation_analytics` ADD PRIMARY KEY (`id`), MODIFY `id` int(11) NOT NULL AUTO_INCREMENT;
ALTER TABLE `consultation_logs` ADD PRIMARY KEY (`id`), MODIFY `id` int(11) NOT NULL AUTO_INCREMENT;
ALTER TABLE `consultation_stages` ADD PRIMARY KEY (`id`), MODIFY `id` int(11) NOT NULL AUTO_INCREMENT;
ALTER TABLE `conversation_assignees` ADD PRIMARY KEY (`id`), MODIFY `id` int(11) NOT NULL AUTO_INCREMENT;
ALTER TABLE `conversation_assignments` ADD PRIMARY KEY (`id`), MODIFY `id` int(11) NOT NULL AUTO_INCREMENT;
ALTER TABLE `conversation_multi_assignees` ADD PRIMARY KEY (`id`), MODIFY `id` int(11) NOT NULL AUTO_INCREMENT;
ALTER TABLE `conversation_states` ADD PRIMARY KEY (`id`), MODIFY `id` int(11) NOT NULL AUTO_INCREMENT;
ALTER TABLE `coupons` ADD PRIMARY KEY (`id`), MODIFY `id` int(11) NOT NULL AUTO_INCREMENT;
ALTER TABLE `coupon_usage` ADD PRIMARY KEY (`id`), MODIFY `id` int(11) NOT NULL AUTO_INCREMENT;
ALTER TABLE `customer_health_profiles` ADD PRIMARY KEY (`id`), MODIFY `id` int(11) NOT NULL AUTO_INCREMENT;
ALTER TABLE `customer_notes` ADD PRIMARY KEY (`id`), MODIFY `id` int(11) NOT NULL AUTO_INCREMENT;
ALTER TABLE `customer_segments` ADD PRIMARY KEY (`id`), MODIFY `id` int(11) NOT NULL AUTO_INCREMENT;
ALTER TABLE `data_access_logs` ADD PRIMARY KEY (`id`), MODIFY `id` int(11) NOT NULL AUTO_INCREMENT;
ALTER TABLE `dev_logs` ADD PRIMARY KEY (`id`), MODIFY `id` int(11) NOT NULL AUTO_INCREMENT;
ALTER TABLE `dispensing_records` ADD PRIMARY KEY (`id`), MODIFY `id` int(11) NOT NULL AUTO_INCREMENT;
ALTER TABLE `drip_campaigns` ADD PRIMARY KEY (`id`), MODIFY `id` int(11) NOT NULL AUTO_INCREMENT;
ALTER TABLE `drip_campaign_logs` ADD PRIMARY KEY (`id`), MODIFY `id` int(11) NOT NULL AUTO_INCREMENT;
ALTER TABLE `drip_campaign_progress` ADD PRIMARY KEY (`id`), MODIFY `id` int(11) NOT NULL AUTO_INCREMENT;
ALTER TABLE `drip_campaign_queue` ADD PRIMARY KEY (`id`), MODIFY `id` int(11) NOT NULL AUTO_INCREMENT;
ALTER TABLE `drip_campaign_steps` ADD PRIMARY KEY (`id`), MODIFY `id` int(11) NOT NULL AUTO_INCREMENT;
ALTER TABLE `drug_disposal_records` ADD PRIMARY KEY (`id`), MODIFY `id` int(11) NOT NULL AUTO_INCREMENT;
ALTER TABLE `drug_interactions` ADD PRIMARY KEY (`id`), MODIFY `id` int(11) NOT NULL AUTO_INCREMENT;
ALTER TABLE `drug_interaction_acknowledgments` ADD PRIMARY KEY (`id`), MODIFY `id` int(11) NOT NULL AUTO_INCREMENT;
ALTER TABLE `drug_pricing_rules` ADD PRIMARY KEY (`id`), MODIFY `id` int(11) NOT NULL AUTO_INCREMENT;
ALTER TABLE `drug_recognition_cache` ADD PRIMARY KEY (`id`), MODIFY `id` int(11) NOT NULL AUTO_INCREMENT;
ALTER TABLE `email_settings` ADD PRIMARY KEY (`id`), MODIFY `id` int(11) NOT NULL AUTO_INCREMENT;
ALTER TABLE `emergency_alerts` ADD PRIMARY KEY (`id`), MODIFY `id` int(11) NOT NULL AUTO_INCREMENT;
ALTER TABLE `expenses` ADD PRIMARY KEY (`id`), MODIFY `id` int(11) NOT NULL AUTO_INCREMENT;
ALTER TABLE `expense_categories` ADD PRIMARY KEY (`id`), MODIFY `id` int(11) NOT NULL AUTO_INCREMENT;
ALTER TABLE `facebook_accounts` ADD PRIMARY KEY (`id`), MODIFY `id` int(11) NOT NULL AUTO_INCREMENT;
ALTER TABLE `flex_templates` ADD PRIMARY KEY (`id`), MODIFY `id` int(11) NOT NULL AUTO_INCREMENT;
ALTER TABLE `ghost_drafts` ADD PRIMARY KEY (`id`), MODIFY `id` int(11) NOT NULL AUTO_INCREMENT;
ALTER TABLE `ghost_draft_learning` ADD PRIMARY KEY (`id`), MODIFY `id` int(11) NOT NULL AUTO_INCREMENT;
ALTER TABLE `goods_receives` ADD PRIMARY KEY (`id`), MODIFY `id` int(11) NOT NULL AUTO_INCREMENT;
ALTER TABLE `goods_receive_items` ADD PRIMARY KEY (`id`), MODIFY `id` int(11) NOT NULL AUTO_INCREMENT;
ALTER TABLE `groups` ADD PRIMARY KEY (`id`), MODIFY `id` int(11) NOT NULL AUTO_INCREMENT;
ALTER TABLE `health_articles` ADD PRIMARY KEY (`id`), MODIFY `id` int(11) NOT NULL AUTO_INCREMENT;
ALTER TABLE `health_article_categories` ADD PRIMARY KEY (`id`), MODIFY `id` int(11) NOT NULL AUTO_INCREMENT;
ALTER TABLE `image_analysis_results` ADD PRIMARY KEY (`id`), MODIFY `id` int(11) NOT NULL AUTO_INCREMENT;
ALTER TABLE `inbox_admin_activity_log` ADD PRIMARY KEY (`id`);
ALTER TABLE `inbox_admin_bot_access` ADD PRIMARY KEY (`id`);
ALTER TABLE `inbox_admin_users` ADD PRIMARY KEY (`id`);
ALTER TABLE `inbox_auth_accounts` ADD PRIMARY KEY (`id`);
ALTER TABLE `inbox_auth_sessions` ADD PRIMARY KEY (`id`);
ALTER TABLE `inbox_auth_users` ADD PRIMARY KEY (`id`);
ALTER TABLE `inbox_auto_tag_rules` ADD PRIMARY KEY (`id`);
ALTER TABLE `inbox_conversation_assignments` ADD PRIMARY KEY (`id`);
ALTER TABLE `inbox_line_accounts` ADD PRIMARY KEY (`id`), MODIFY `id` int(11) NOT NULL AUTO_INCREMENT;
ALTER TABLE `inbox_line_users` ADD PRIMARY KEY (`id`);
ALTER TABLE `inbox_messages` ADD PRIMARY KEY (`id`);
ALTER TABLE `inbox_user_tags` ADD PRIMARY KEY (`id`);
ALTER TABLE `inbox_user_tag_assignments` ADD PRIMARY KEY (`id`);
ALTER TABLE `inventory_batches` ADD PRIMARY KEY (`id`), MODIFY `id` int(11) NOT NULL AUTO_INCREMENT;
ALTER TABLE `item_categories` ADD PRIMARY KEY (`id`), MODIFY `id` int(11) NOT NULL AUTO_INCREMENT;
ALTER TABLE `item_images` ADD PRIMARY KEY (`id`), MODIFY `id` int(11) NOT NULL AUTO_INCREMENT;
ALTER TABLE `landing_banners` ADD PRIMARY KEY (`id`), MODIFY `id` int(11) NOT NULL AUTO_INCREMENT;
ALTER TABLE `landing_faqs` ADD PRIMARY KEY (`id`), MODIFY `id` int(11) NOT NULL AUTO_INCREMENT;
ALTER TABLE `landing_featured_products` ADD PRIMARY KEY (`id`), MODIFY `id` int(11) NOT NULL AUTO_INCREMENT;
ALTER TABLE `landing_settings` ADD PRIMARY KEY (`id`), MODIFY `id` int(11) NOT NULL AUTO_INCREMENT;
ALTER TABLE `landing_testimonials` ADD PRIMARY KEY (`id`), MODIFY `id` int(11) NOT NULL AUTO_INCREMENT;
ALTER TABLE `liff_apps` ADD PRIMARY KEY (`id`), MODIFY `id` int(11) NOT NULL AUTO_INCREMENT;
ALTER TABLE `liff_message_logs` ADD PRIMARY KEY (`id`), MODIFY `id` int(11) NOT NULL AUTO_INCREMENT;
ALTER TABLE `liff_shop_settings` ADD PRIMARY KEY (`id`), MODIFY `id` int(11) NOT NULL AUTO_INCREMENT;
ALTER TABLE `line_groups` ADD PRIMARY KEY (`id`), MODIFY `id` int(11) NOT NULL AUTO_INCREMENT;
ALTER TABLE `line_group_members` ADD PRIMARY KEY (`id`), MODIFY `id` int(11) NOT NULL AUTO_INCREMENT;
ALTER TABLE `line_group_messages` ADD PRIMARY KEY (`id`), MODIFY `id` int(11) NOT NULL AUTO_INCREMENT;
ALTER TABLE `link_clicks` ADD PRIMARY KEY (`id`), MODIFY `id` int(11) NOT NULL AUTO_INCREMENT;
ALTER TABLE `location_movements` ADD PRIMARY KEY (`id`), MODIFY `id` int(11) NOT NULL AUTO_INCREMENT;
ALTER TABLE `loyalty_points` ADD PRIMARY KEY (`id`), MODIFY `id` int(11) NOT NULL AUTO_INCREMENT;
ALTER TABLE `loyalty_points_history` ADD PRIMARY KEY (`id`), MODIFY `id` int(11) NOT NULL AUTO_INCREMENT;
ALTER TABLE `medical_history` ADD PRIMARY KEY (`id`), MODIFY `id` int(11) NOT NULL AUTO_INCREMENT;
ALTER TABLE `medication_reminders` ADD PRIMARY KEY (`id`), MODIFY `id` int(11) NOT NULL AUTO_INCREMENT;
ALTER TABLE `medication_taken_history` ADD PRIMARY KEY (`id`), MODIFY `id` int(11) NOT NULL AUTO_INCREMENT;
ALTER TABLE `messages` ADD PRIMARY KEY (`id`), MODIFY `id` int(11) NOT NULL AUTO_INCREMENT;
ALTER TABLE `message_analytics` ADD PRIMARY KEY (`id`), MODIFY `id` int(11) NOT NULL AUTO_INCREMENT;
ALTER TABLE `mims_conversation_state` ADD PRIMARY KEY (`id`), MODIFY `id` int(11) NOT NULL AUTO_INCREMENT;
ALTER TABLE `notification_settings` ADD PRIMARY KEY (`id`), MODIFY `id` int(11) NOT NULL AUTO_INCREMENT;
ALTER TABLE `odoo_activity_log` ADD PRIMARY KEY (`id`), MODIFY `id` int(11) NOT NULL AUTO_INCREMENT;
ALTER TABLE `odoo_api_logs` ADD PRIMARY KEY (`id`), MODIFY `id` int(11) NOT NULL AUTO_INCREMENT;
ALTER TABLE `odoo_bdos` ADD PRIMARY KEY (`id`), MODIFY `id` bigint(20) unsigned NOT NULL AUTO_INCREMENT;
ALTER TABLE `odoo_bdos_broken` ADD PRIMARY KEY (`id`), MODIFY `id` bigint(20) unsigned NOT NULL AUTO_INCREMENT;
ALTER TABLE `odoo_bdos_old` ADD PRIMARY KEY (`id`), MODIFY `id` bigint(20) unsigned NOT NULL AUTO_INCREMENT;
ALTER TABLE `odoo_bdos_old2` ADD PRIMARY KEY (`id`), MODIFY `id` bigint(20) unsigned NOT NULL AUTO_INCREMENT;
ALTER TABLE `odoo_bdo_context` ADD PRIMARY KEY (`id`), MODIFY `id` int(11) NOT NULL AUTO_INCREMENT;
ALTER TABLE `odoo_bdo_orders` ADD PRIMARY KEY (`id`), MODIFY `id` int(11) NOT NULL AUTO_INCREMENT;
ALTER TABLE `odoo_customers_cache` ADD PRIMARY KEY (`id`), MODIFY `id` int(10) unsigned NOT NULL AUTO_INCREMENT;
ALTER TABLE `odoo_customer_product_stats` ADD PRIMARY KEY (`id`), MODIFY `id` int(11) NOT NULL AUTO_INCREMENT;
ALTER TABLE `odoo_customer_projection` ADD PRIMARY KEY (`id`), MODIFY `id` int(11) NOT NULL AUTO_INCREMENT;
ALTER TABLE `odoo_daily_summary` ADD PRIMARY KEY (`id`), MODIFY `id` int(11) NOT NULL AUTO_INCREMENT;
ALTER TABLE `odoo_daily_summary_auto_log` ADD PRIMARY KEY (`id`), MODIFY `id` int(10) unsigned NOT NULL AUTO_INCREMENT;
ALTER TABLE `odoo_daily_summary_settings` ADD PRIMARY KEY (`id`), MODIFY `id` int(10) unsigned NOT NULL AUTO_INCREMENT;
ALTER TABLE `odoo_dashboard_cache_meta` ADD PRIMARY KEY (`id`), MODIFY `id` int(10) unsigned NOT NULL AUTO_INCREMENT;
ALTER TABLE `odoo_invoices` ADD PRIMARY KEY (`id`), MODIFY `id` bigint(20) unsigned NOT NULL AUTO_INCREMENT;
ALTER TABLE `odoo_invoices_broken` ADD PRIMARY KEY (`id`), MODIFY `id` bigint(20) unsigned NOT NULL AUTO_INCREMENT;
ALTER TABLE `odoo_invoices_cache` ADD PRIMARY KEY (`id`), MODIFY `id` int(10) unsigned NOT NULL AUTO_INCREMENT;
ALTER TABLE `odoo_invoices_old` ADD PRIMARY KEY (`id`), MODIFY `id` int(11) NOT NULL AUTO_INCREMENT;
ALTER TABLE `odoo_invoices_old2` ADD PRIMARY KEY (`id`), MODIFY `id` bigint(20) unsigned NOT NULL AUTO_INCREMENT;
ALTER TABLE `odoo_line_users` ADD PRIMARY KEY (`id`), MODIFY `id` int(11) NOT NULL AUTO_INCREMENT;
ALTER TABLE `odoo_manual_overrides` ADD PRIMARY KEY (`id`), MODIFY `id` int(11) NOT NULL AUTO_INCREMENT;
ALTER TABLE `odoo_notification_batch_groups` ADD PRIMARY KEY (`id`), MODIFY `id` int(11) NOT NULL AUTO_INCREMENT;
ALTER TABLE `odoo_notification_log` ADD PRIMARY KEY (`id`), MODIFY `id` int(11) NOT NULL AUTO_INCREMENT;
ALTER TABLE `odoo_notification_preferences` ADD PRIMARY KEY (`id`), MODIFY `id` int(11) NOT NULL AUTO_INCREMENT;
ALTER TABLE `odoo_notification_queue` ADD PRIMARY KEY (`id`), MODIFY `id` int(11) NOT NULL AUTO_INCREMENT;
ALTER TABLE `odoo_notification_templates` ADD PRIMARY KEY (`id`), MODIFY `id` int(11) NOT NULL AUTO_INCREMENT;
ALTER TABLE `odoo_orders` ADD PRIMARY KEY (`id`), MODIFY `id` bigint(20) unsigned NOT NULL AUTO_INCREMENT;
ALTER TABLE `odoo_orders_old` ADD PRIMARY KEY (`id`), MODIFY `id` int(11) NOT NULL AUTO_INCREMENT;
ALTER TABLE `odoo_orders_summary` ADD PRIMARY KEY (`id`), MODIFY `id` int(10) unsigned NOT NULL AUTO_INCREMENT;
ALTER TABLE `odoo_order_events` ADD PRIMARY KEY (`id`), MODIFY `id` int(10) unsigned NOT NULL AUTO_INCREMENT;
ALTER TABLE `odoo_order_lines` ADD PRIMARY KEY (`id`), MODIFY `id` int(11) NOT NULL AUTO_INCREMENT;
ALTER TABLE `odoo_order_notes` ADD PRIMARY KEY (`id`), MODIFY `id` int(11) NOT NULL AUTO_INCREMENT;
ALTER TABLE `odoo_order_projection` ADD PRIMARY KEY (`id`), MODIFY `id` int(11) NOT NULL AUTO_INCREMENT;
ALTER TABLE `odoo_order_states` ADD PRIMARY KEY (`id`), MODIFY `id` int(11) NOT NULL AUTO_INCREMENT;
ALTER TABLE `odoo_order_status_overrides` ADD PRIMARY KEY (`id`), MODIFY `id` int(11) NOT NULL AUTO_INCREMENT;
ALTER TABLE `odoo_payments` ADD PRIMARY KEY (`id`), MODIFY `id` int(11) NOT NULL AUTO_INCREMENT;
ALTER TABLE `odoo_products_cache` ADD PRIMARY KEY (`id`), MODIFY `id` int(11) NOT NULL AUTO_INCREMENT;
ALTER TABLE `odoo_slips_cache` ADD PRIMARY KEY (`id`), MODIFY `id` int(10) unsigned NOT NULL AUTO_INCREMENT;
ALTER TABLE `odoo_slip_uploads` ADD PRIMARY KEY (`id`), MODIFY `id` int(11) NOT NULL AUTO_INCREMENT;
ALTER TABLE `odoo_sync_log` ADD PRIMARY KEY (`id`), MODIFY `id` int(10) unsigned NOT NULL AUTO_INCREMENT;
ALTER TABLE `odoo_webhooks_log` ADD PRIMARY KEY (`id`), MODIFY `id` int(11) NOT NULL AUTO_INCREMENT;
ALTER TABLE `odoo_webhook_dlq` ADD PRIMARY KEY (`id`), MODIFY `id` int(11) NOT NULL AUTO_INCREMENT;
ALTER TABLE `odoo_webhook_logs` ADD PRIMARY KEY (`id`), MODIFY `id` int(11) NOT NULL AUTO_INCREMENT;
ALTER TABLE `onboarding_sessions` ADD PRIMARY KEY (`id`), MODIFY `id` int(11) NOT NULL AUTO_INCREMENT;
ALTER TABLE `orders` ADD PRIMARY KEY (`id`), MODIFY `id` int(11) NOT NULL AUTO_INCREMENT;
ALTER TABLE `order_items` ADD PRIMARY KEY (`id`), MODIFY `id` int(11) NOT NULL AUTO_INCREMENT;
ALTER TABLE `payment_proofs` ADD PRIMARY KEY (`id`), MODIFY `id` int(11) NOT NULL AUTO_INCREMENT;
ALTER TABLE `payment_slips` ADD PRIMARY KEY (`id`), MODIFY `id` int(11) NOT NULL AUTO_INCREMENT;
ALTER TABLE `payment_vouchers` ADD PRIMARY KEY (`id`), MODIFY `id` int(11) NOT NULL AUTO_INCREMENT;
ALTER TABLE `performance_metrics` ADD PRIMARY KEY (`id`), MODIFY `id` int(11) NOT NULL AUTO_INCREMENT;
ALTER TABLE `pharmacists` ADD PRIMARY KEY (`id`), MODIFY `id` int(11) NOT NULL AUTO_INCREMENT;
ALTER TABLE `pharmacist_consultations` ADD PRIMARY KEY (`id`), MODIFY `id` int(11) NOT NULL AUTO_INCREMENT;
ALTER TABLE `pharmacist_holidays` ADD PRIMARY KEY (`id`), MODIFY `id` int(11) NOT NULL AUTO_INCREMENT;
ALTER TABLE `pharmacist_notifications` ADD PRIMARY KEY (`id`), MODIFY `id` int(11) NOT NULL AUTO_INCREMENT;
ALTER TABLE `pharmacist_schedules` ADD PRIMARY KEY (`id`), MODIFY `id` int(11) NOT NULL AUTO_INCREMENT;
ALTER TABLE `pharmacy_context_keywords` ADD PRIMARY KEY (`id`), MODIFY `id` int(11) NOT NULL AUTO_INCREMENT;
ALTER TABLE `pharmacy_ghost_learning` ADD PRIMARY KEY (`id`), MODIFY `id` int(11) NOT NULL AUTO_INCREMENT;
ALTER TABLE `points_campaigns` ADD PRIMARY KEY (`id`), MODIFY `id` int(11) NOT NULL AUTO_INCREMENT;
ALTER TABLE `points_history` ADD PRIMARY KEY (`id`), MODIFY `id` int(11) NOT NULL AUTO_INCREMENT;
ALTER TABLE `points_rules` ADD PRIMARY KEY (`id`), MODIFY `id` int(11) NOT NULL AUTO_INCREMENT;
ALTER TABLE `points_settings` ADD PRIMARY KEY (`id`), MODIFY `id` int(11) NOT NULL AUTO_INCREMENT;
ALTER TABLE `points_tiers` ADD PRIMARY KEY (`id`), MODIFY `id` int(11) NOT NULL AUTO_INCREMENT;
ALTER TABLE `points_transactions` ADD PRIMARY KEY (`id`), MODIFY `id` int(11) NOT NULL AUTO_INCREMENT;
ALTER TABLE `point_rewards` ADD PRIMARY KEY (`id`), MODIFY `id` int(11) NOT NULL AUTO_INCREMENT;
ALTER TABLE `pos_cash_movements` ADD PRIMARY KEY (`id`), MODIFY `id` int(11) NOT NULL AUTO_INCREMENT;
ALTER TABLE `pos_daily_summary` ADD PRIMARY KEY (`id`), MODIFY `id` int(11) NOT NULL AUTO_INCREMENT;
ALTER TABLE `pos_payments` ADD PRIMARY KEY (`id`), MODIFY `id` int(11) NOT NULL AUTO_INCREMENT;
ALTER TABLE `pos_returns` ADD PRIMARY KEY (`id`), MODIFY `id` int(11) NOT NULL AUTO_INCREMENT;
ALTER TABLE `pos_return_items` ADD PRIMARY KEY (`id`), MODIFY `id` int(11) NOT NULL AUTO_INCREMENT;
ALTER TABLE `pos_shifts` ADD PRIMARY KEY (`id`), MODIFY `id` int(11) NOT NULL AUTO_INCREMENT;
ALTER TABLE `pos_transactions` ADD PRIMARY KEY (`id`), MODIFY `id` int(11) NOT NULL AUTO_INCREMENT;
ALTER TABLE `pos_transaction_items` ADD PRIMARY KEY (`id`), MODIFY `id` int(11) NOT NULL AUTO_INCREMENT;
ALTER TABLE `prescription_approvals` ADD PRIMARY KEY (`id`), MODIFY `id` int(11) NOT NULL AUTO_INCREMENT;
ALTER TABLE `prescription_items` ADD PRIMARY KEY (`id`), MODIFY `id` int(11) NOT NULL AUTO_INCREMENT;
ALTER TABLE `prescription_ocr_results` ADD PRIMARY KEY (`id`), MODIFY `id` int(11) NOT NULL AUTO_INCREMENT;
ALTER TABLE `prescription_records` ADD PRIMARY KEY (`id`), MODIFY `id` int(11) NOT NULL AUTO_INCREMENT;
ALTER TABLE `products` ADD PRIMARY KEY (`id`), MODIFY `id` int(11) NOT NULL AUTO_INCREMENT;
ALTER TABLE `product_categories` ADD PRIMARY KEY (`id`), MODIFY `id` int(11) NOT NULL AUTO_INCREMENT;
ALTER TABLE `product_images` ADD PRIMARY KEY (`id`), MODIFY `id` int(11) NOT NULL AUTO_INCREMENT;
ALTER TABLE `product_units` ADD PRIMARY KEY (`id`), MODIFY `id` int(11) NOT NULL AUTO_INCREMENT;
ALTER TABLE `promotion_settings` ADD PRIMARY KEY (`id`), MODIFY `id` int(11) NOT NULL AUTO_INCREMENT;
ALTER TABLE `purchase_orders` ADD PRIMARY KEY (`id`), MODIFY `id` int(11) NOT NULL AUTO_INCREMENT;
ALTER TABLE `purchase_order_items` ADD PRIMARY KEY (`id`), MODIFY `id` int(11) NOT NULL AUTO_INCREMENT;
ALTER TABLE `quick_reply_templates` ADD PRIMARY KEY (`id`), MODIFY `id` int(11) NOT NULL AUTO_INCREMENT;
ALTER TABLE `receipt_vouchers` ADD PRIMARY KEY (`id`), MODIFY `id` int(11) NOT NULL AUTO_INCREMENT;
ALTER TABLE `red_flag_symptoms` ADD PRIMARY KEY (`id`), MODIFY `id` int(11) NOT NULL AUTO_INCREMENT;
ALTER TABLE `restock_notifications` ADD PRIMARY KEY (`id`), MODIFY `id` int(11) NOT NULL AUTO_INCREMENT;
ALTER TABLE `retail_banners` ADD PRIMARY KEY (`id`), MODIFY `id` int(11) NOT NULL AUTO_INCREMENT;
ALTER TABLE `retail_cart` ADD PRIMARY KEY (`id`), MODIFY `id` int(11) NOT NULL AUTO_INCREMENT;
ALTER TABLE `retail_categories` ADD PRIMARY KEY (`id`), MODIFY `id` int(11) NOT NULL AUTO_INCREMENT;
ALTER TABLE `retail_orders` ADD PRIMARY KEY (`id`), MODIFY `id` int(11) NOT NULL AUTO_INCREMENT;
ALTER TABLE `retail_order_items_temp` ADD PRIMARY KEY (`id`), MODIFY `id` int(11) NOT NULL AUTO_INCREMENT;
ALTER TABLE `retail_order_status_history` ADD PRIMARY KEY (`id`), MODIFY `id` int(11) NOT NULL AUTO_INCREMENT;
ALTER TABLE `retail_products` ADD PRIMARY KEY (`id`), MODIFY `id` int(11) NOT NULL AUTO_INCREMENT;
ALTER TABLE `retail_promotions` ADD PRIMARY KEY (`id`), MODIFY `id` int(11) NOT NULL AUTO_INCREMENT;
ALTER TABLE `retail_settings` ADD PRIMARY KEY (`id`), MODIFY `id` int(11) NOT NULL AUTO_INCREMENT;
ALTER TABLE `retail_users` ADD PRIMARY KEY (`id`), MODIFY `id` int(11) NOT NULL AUTO_INCREMENT;
ALTER TABLE `rewards` ADD PRIMARY KEY (`id`), MODIFY `id` int(11) NOT NULL AUTO_INCREMENT;
ALTER TABLE `reward_redemptions` ADD PRIMARY KEY (`id`), MODIFY `id` int(11) NOT NULL AUTO_INCREMENT;
ALTER TABLE `rich_menus` ADD PRIMARY KEY (`id`), MODIFY `id` int(11) NOT NULL AUTO_INCREMENT;
ALTER TABLE `rich_menu_aliases` ADD PRIMARY KEY (`id`), MODIFY `id` int(11) NOT NULL AUTO_INCREMENT;
ALTER TABLE `rich_menu_rules` ADD PRIMARY KEY (`id`), MODIFY `id` int(11) NOT NULL AUTO_INCREMENT;
ALTER TABLE `rich_menu_switch_log` ADD PRIMARY KEY (`id`), MODIFY `id` int(11) NOT NULL AUTO_INCREMENT;
ALTER TABLE `rich_menu_switch_pages` ADD PRIMARY KEY (`id`), MODIFY `id` int(11) NOT NULL AUTO_INCREMENT;
ALTER TABLE `rich_menu_switch_sets` ADD PRIMARY KEY (`id`), MODIFY `id` int(11) NOT NULL AUTO_INCREMENT;
ALTER TABLE `scheduled_messages` ADD PRIMARY KEY (`id`), MODIFY `id` int(11) NOT NULL AUTO_INCREMENT;
ALTER TABLE `scheduled_reports` ADD PRIMARY KEY (`id`), MODIFY `id` int(11) NOT NULL AUTO_INCREMENT;
ALTER TABLE `scheduled_report_logs` ADD PRIMARY KEY (`id`), MODIFY `id` int(11) NOT NULL AUTO_INCREMENT;
ALTER TABLE `scheduled_report_recipients` ADD PRIMARY KEY (`id`), MODIFY `id` int(11) NOT NULL AUTO_INCREMENT;
ALTER TABLE `settings` ADD PRIMARY KEY (`id`), MODIFY `id` int(11) NOT NULL AUTO_INCREMENT;
ALTER TABLE `setup_progress` ADD PRIMARY KEY (`id`), MODIFY `id` int(11) NOT NULL AUTO_INCREMENT;
ALTER TABLE `shared_flex_messages` ADD PRIMARY KEY (`id`), MODIFY `id` int(11) NOT NULL AUTO_INCREMENT;
ALTER TABLE `shop_settings` ADD PRIMARY KEY (`id`), MODIFY `id` int(11) NOT NULL AUTO_INCREMENT;
ALTER TABLE `sla_tracking` ADD PRIMARY KEY (`id`), MODIFY `id` int(11) NOT NULL AUTO_INCREMENT;
ALTER TABLE `slip_verifications` ADD PRIMARY KEY (`id`), MODIFY `id` int(11) NOT NULL AUTO_INCREMENT;
ALTER TABLE `stock_adjustments` ADD PRIMARY KEY (`id`), MODIFY `id` int(11) NOT NULL AUTO_INCREMENT;
ALTER TABLE `stock_movements` ADD PRIMARY KEY (`id`), MODIFY `id` int(11) NOT NULL AUTO_INCREMENT;
ALTER TABLE `suppliers` ADD PRIMARY KEY (`id`), MODIFY `id` int(11) NOT NULL AUTO_INCREMENT;
ALTER TABLE `symptom_analysis_cache` ADD PRIMARY KEY (`id`), MODIFY `id` int(11) NOT NULL AUTO_INCREMENT;
ALTER TABLE `symptom_assessments` ADD PRIMARY KEY (`id`), MODIFY `id` int(11) NOT NULL AUTO_INCREMENT;
ALTER TABLE `symptom_assessment_followups` ADD PRIMARY KEY (`id`), MODIFY `id` int(11) NOT NULL AUTO_INCREMENT;
ALTER TABLE `sync_batches` ADD PRIMARY KEY (`id`), MODIFY `id` int(11) NOT NULL AUTO_INCREMENT;
ALTER TABLE `sync_logs` ADD PRIMARY KEY (`id`), MODIFY `id` int(11) NOT NULL AUTO_INCREMENT;
ALTER TABLE `sync_queue` ADD PRIMARY KEY (`id`), MODIFY `id` int(11) NOT NULL AUTO_INCREMENT;
ALTER TABLE `tags` ADD PRIMARY KEY (`id`), MODIFY `id` int(11) NOT NULL AUTO_INCREMENT;
ALTER TABLE `temperature_logs` ADD PRIMARY KEY (`id`), MODIFY `id` int(11) NOT NULL AUTO_INCREMENT;
ALTER TABLE `templates` ADD PRIMARY KEY (`id`), MODIFY `id` int(11) NOT NULL AUTO_INCREMENT;
ALTER TABLE `testing_results` ADD PRIMARY KEY (`id`), MODIFY `id` int(11) NOT NULL AUTO_INCREMENT;
ALTER TABLE `tier_settings` ADD PRIMARY KEY (`id`), MODIFY `id` int(11) NOT NULL AUTO_INCREMENT;
ALTER TABLE `tiktok_shop_accounts` ADD PRIMARY KEY (`id`), MODIFY `id` int(11) NOT NULL AUTO_INCREMENT;
ALTER TABLE `tracked_links` ADD PRIMARY KEY (`id`), MODIFY `id` int(11) NOT NULL AUTO_INCREMENT;
ALTER TABLE `transactions` ADD PRIMARY KEY (`id`), MODIFY `id` int(11) NOT NULL AUTO_INCREMENT;
ALTER TABLE `transaction_items` ADD PRIMARY KEY (`id`), MODIFY `id` int(11) NOT NULL AUTO_INCREMENT;
ALTER TABLE `triage_analytics` ADD PRIMARY KEY (`id`), MODIFY `id` int(11) NOT NULL AUTO_INCREMENT;
ALTER TABLE `triage_sessions` ADD PRIMARY KEY (`id`), MODIFY `id` int(11) NOT NULL AUTO_INCREMENT;
ALTER TABLE `users` ADD PRIMARY KEY (`id`), MODIFY `id` int(11) NOT NULL AUTO_INCREMENT;
ALTER TABLE `user_behaviors` ADD PRIMARY KEY (`id`), MODIFY `id` int(11) NOT NULL AUTO_INCREMENT;
ALTER TABLE `user_consents` ADD PRIMARY KEY (`id`), MODIFY `id` int(11) NOT NULL AUTO_INCREMENT;
ALTER TABLE `user_current_medications` ADD PRIMARY KEY (`id`), MODIFY `id` int(11) NOT NULL AUTO_INCREMENT;
ALTER TABLE `user_custom_fields` ADD PRIMARY KEY (`id`), MODIFY `id` int(11) NOT NULL AUTO_INCREMENT;
ALTER TABLE `user_custom_field_values` ADD PRIMARY KEY (`id`), MODIFY `id` int(11) NOT NULL AUTO_INCREMENT;
ALTER TABLE `user_drug_allergies` ADD PRIMARY KEY (`id`), MODIFY `id` int(11) NOT NULL AUTO_INCREMENT;
ALTER TABLE `user_health_profiles` ADD PRIMARY KEY (`id`), MODIFY `id` int(11) NOT NULL AUTO_INCREMENT;
ALTER TABLE `user_notes` ADD PRIMARY KEY (`id`), MODIFY `id` int(11) NOT NULL AUTO_INCREMENT;
ALTER TABLE `user_notification_preferences` ADD PRIMARY KEY (`id`), MODIFY `id` int(11) NOT NULL AUTO_INCREMENT;
ALTER TABLE `user_notification_settings` ADD PRIMARY KEY (`id`), MODIFY `id` int(11) NOT NULL AUTO_INCREMENT;
ALTER TABLE `user_points` ADD PRIMARY KEY (`id`), MODIFY `id` int(11) NOT NULL AUTO_INCREMENT;
ALTER TABLE `user_rich_menus` ADD PRIMARY KEY (`id`), MODIFY `id` int(11) NOT NULL AUTO_INCREMENT;
ALTER TABLE `user_tags` ADD PRIMARY KEY (`id`), MODIFY `id` int(11) NOT NULL AUTO_INCREMENT;
ALTER TABLE `user_tag_assignments` ADD PRIMARY KEY (`id`), MODIFY `id` int(11) NOT NULL AUTO_INCREMENT;
ALTER TABLE `user_wishlist` ADD PRIMARY KEY (`id`), MODIFY `id` int(11) NOT NULL AUTO_INCREMENT;
ALTER TABLE `vibe_selling_settings` ADD PRIMARY KEY (`id`), MODIFY `id` int(11) NOT NULL AUTO_INCREMENT;
ALTER TABLE `video_calls` ADD PRIMARY KEY (`id`), MODIFY `id` int(11) NOT NULL AUTO_INCREMENT;
ALTER TABLE `video_call_settings` ADD PRIMARY KEY (`id`), MODIFY `id` int(11) NOT NULL AUTO_INCREMENT;
ALTER TABLE `video_call_signals` ADD PRIMARY KEY (`id`), MODIFY `id` int(11) NOT NULL AUTO_INCREMENT;
