<?php
/**
 * LINE CRM Pharmacy - Configuration
 * Generated by Installation Wizard on 2026-01-21 03:09:00
 */
error_reporting(E_ALL & ~E_DEPRECATED & ~E_STRICT);

// mb_internal_encoding('UTF-8'); // Deprecated in PHP 8.2+
mb_http_output('UTF-8');
ini_set('default_charset', 'UTF-8');

ini_set('display_errors', 0);
ini_set('log_errors', 1);


if (session_status() === PHP_SESSION_NONE) {
    session_start();
}

// Database
define('DB_HOST', 'localhost');
define('DB_NAME', 'zrismpsz_clinicya');
define('DB_USER', 'zrismpsz_clinicya');
define('DB_PASS', 'zrismpsz_clinicya');

// Application
define('APP_NAME', 'CLINICYA REYA');
define('APP_URL', 'https://clinicya.re-ya.com/');
define('BASE_URL', 'https://clinicya.re-ya.com/');
define('TIMEZONE', 'Asia/Bangkok');

// LINE API (ตั้งค่าผ่านหน้า Admin)
define('LINE_CHANNEL_ACCESS_TOKEN', '');
define('LINE_CHANNEL_SECRET', '');

// Table Names
define('TABLE_USERS', 'users');
define('TABLE_GROUPS', 'groups');
// Next.js API Integration
// URL ของ Next.js app (ปรับตาม environment)
define('NEXTJS_API_URL', 'https://app.re-ya.com');
// Secret key สำหรับ authentication (ใช้ค่าเดียวกับ Next.js INTERNAL_API_SECRET)

// ============================================================================
// Odoo ERP Integration Configuration
// ============================================================================

// Master kill-switch for the Odoo integration. Set ODOO_INTEGRATION_ENABLED=0
// in env (or leave empty) for tenants that do not use Odoo. When false:
//   - inbound webhook receivers (api/webhook/odoo.php, api/odoo-webhook.php) return 410
//   - outbound api/odoo-*.php endpoints return 410
//   - cron/odoo_*.php and cron/sync_odoo_*.php exit early
//   - per-tenant $isOdooMode (shop_settings.order_data_source) still controls UI separately
$odooEnabledEnv = getenv('ODOO_INTEGRATION_ENABLED');
define(
    'ODOO_INTEGRATION_ENABLED',
    $odooEnabledEnv !== false
        ? in_array(strtolower((string) $odooEnabledEnv), ['1', 'true', 'yes', 'on'], true)
        : false
);

// --- Global Odoo entry-script kill-switch -------------------------------------
// When ODOO_INTEGRATION_ENABLED is false, any HTTP request or CLI invocation
// whose entry script is an Odoo-named file (api/odoo-*, api/webhook/odoo.php,
// api/admin-odoo-*, api/send-slips-to-odoo.php, cron/odoo_*, cron/sync_odoo_*)
// is short-circuited here — before any handler logic loads. Non-Odoo callers
// fall through unchanged.
if (ODOO_INTEGRATION_ENABLED !== true) {
    $odooEntryScript = '';
    if (PHP_SAPI === 'cli') {
        $odooEntryScript = isset($_SERVER['argv'][0]) ? (string) $_SERVER['argv'][0] : '';
    } else {
        $odooEntryScript = isset($_SERVER['SCRIPT_FILENAME']) ? (string) $_SERVER['SCRIPT_FILENAME'] : '';
    }
    $odooEntryScript = str_replace('\\', '/', $odooEntryScript);

    $odooEntryPattern = '#(?:^|/)(?:'
        . 'api/webhook/odoo\.php'
        . '|api/odoo-[\w.\-]+\.php'
        . '|api/admin-odoo-[\w.\-]+\.php'
        . '|api/send-slips-to-odoo\.php'
        . '|cron/odoo_[\w.\-]+\.php'
        . '|cron/sync_odoo_[\w.\-]+\.php'
        . '|odoo\.php'
        . '|odoo-dashboard\.php'
        . '|odoo-customer-detail\.php'
        . ')$#i';
    if ($odooEntryScript !== '' && preg_match($odooEntryPattern, $odooEntryScript)) {
        if (PHP_SAPI === 'cli') {
            fwrite(STDERR, "[odoo-disabled] Skipping {$odooEntryScript} — ODOO_INTEGRATION_ENABLED is false\n");
            exit(0);
        }

        if (!headers_sent()) {
            http_response_code(410);
            header('Content-Type: application/json; charset=utf-8');
        }
        echo json_encode([
            'success'    => false,
            'error'      => 'Odoo integration is not enabled for this tenant',
            'error_code' => 'ODOO_INTEGRATION_DISABLED'
        ]);
        exit;
    }
}
// ------------------------------------------------------------------------------

// Environment: 'staging' or 'production'
// Force production for cny.re-ya.com
define('ODOO_ENVIRONMENT', 'production');

// Staging Configuration
define('ODOO_STAGING_API_BASE_URL', 'https://stg-erp.cnyrxapp.com');
define('ODOO_STAGING_API_KEY', getenv('ODOO_STAGING_API_KEY') ?: '');
define('ODOO_STAGING_WEBHOOK_SECRET', getenv('ODOO_STAGING_WEBHOOK_SECRET') ?: '');

// Production Configuration
define('ODOO_PRODUCTION_API_BASE_URL', getenv('ODOO_PRODUCTION_API_BASE_URL') ?: '');
define('ODOO_PRODUCTION_API_KEY', getenv('ODOO_PRODUCTION_API_KEY') ?: '');
define('ODOO_PRODUCTION_WEBHOOK_SECRET', getenv('ODOO_PRODUCTION_WEBHOOK_SECRET') ?: '');

// Active Configuration (based on environment)
define(
    'ODOO_API_BASE_URL',
    ODOO_ENVIRONMENT === 'production'
    ? ODOO_PRODUCTION_API_BASE_URL
    : ODOO_STAGING_API_BASE_URL
);

define(
    'ODOO_API_KEY',
    ODOO_ENVIRONMENT === 'production'
    ? ODOO_PRODUCTION_API_KEY
    : ODOO_STAGING_API_KEY
);

define(
    'ODOO_WEBHOOK_SECRET',
    ODOO_ENVIRONMENT === 'production'
    ? ODOO_PRODUCTION_WEBHOOK_SECRET
    : ODOO_STAGING_WEBHOOK_SECRET
);

// Webhook verification tolerances (temporary legacy bridge defaults allow +7h skew)
$webhookToleranceEnv = getenv('ODOO_WEBHOOK_TOLERANCE_SECONDS');
define(
    'ODOO_WEBHOOK_TOLERANCE_SECONDS',
    $webhookToleranceEnv !== false ? (int) $webhookToleranceEnv : 300
);

$allowLegacyDriftEnv = getenv('ODOO_WEBHOOK_ALLOW_LEGACY_DRIFT');
define(
    'ODOO_WEBHOOK_ALLOW_LEGACY_DRIFT',
    $allowLegacyDriftEnv === false
        ? true
        : !in_array(strtolower((string) $allowLegacyDriftEnv), ['0', 'false', 'no'], true)
);

$legacyDriftEnv = getenv('ODOO_WEBHOOK_LEGACY_DRIFT_SECONDS');
define(
    'ODOO_WEBHOOK_LEGACY_DRIFT_SECONDS',
    $legacyDriftEnv !== false ? (int) $legacyDriftEnv : (7 * 3600)
);

$legacyDriftToleranceEnv = getenv('ODOO_WEBHOOK_LEGACY_DRIFT_TOLERANCE');
define(
    'ODOO_WEBHOOK_LEGACY_DRIFT_TOLERANCE',
    $legacyDriftToleranceEnv !== false ? (int) $legacyDriftToleranceEnv : 120
);

// Odoo API Settings
$odooApiTimeoutEnv = getenv('ODOO_API_TIMEOUT');
$odooApiConnectTimeoutEnv = getenv('ODOO_API_CONNECT_TIMEOUT');
$odooApiRetryLimitEnv = getenv('ODOO_API_RETRY_LIMIT');
$odooApiDebugEnv = getenv('ODOO_API_DEBUG_LOG');
$odooWebhookDebugEnv = getenv('ODOO_WEBHOOK_DEBUG_LOG');
$odooWebhookSignatureDebugEnv = getenv('ODOO_WEBHOOK_SIGNATURE_DEBUG');
$odooDashboardStaleEnv = getenv('ODOO_DASHBOARD_STALE_TTL');

define('ODOO_API_TIMEOUT', $odooApiTimeoutEnv !== false ? max(5, (int) $odooApiTimeoutEnv) : 15); // seconds
define('ODOO_API_CONNECT_TIMEOUT', $odooApiConnectTimeoutEnv !== false ? max(1, (int) $odooApiConnectTimeoutEnv) : 3); // seconds
define('ODOO_API_RETRY_LIMIT', $odooApiRetryLimitEnv !== false ? max(0, (int) $odooApiRetryLimitEnv) : 1); // transient retries
define(
    'ODOO_API_DEBUG_LOG',
    $odooApiDebugEnv !== false && in_array(strtolower((string) $odooApiDebugEnv), ['1', 'true', 'yes', 'on'], true)
);
define(
    'ODOO_WEBHOOK_DEBUG_LOG',
    $odooWebhookDebugEnv !== false && in_array(strtolower((string) $odooWebhookDebugEnv), ['1', 'true', 'yes', 'on'], true)
);
define(
    'ODOO_WEBHOOK_SIGNATURE_DEBUG',
    $odooWebhookSignatureDebugEnv !== false && in_array(strtolower((string) $odooWebhookSignatureDebugEnv), ['1', 'true', 'yes', 'on'], true)
);
define('ODOO_API_RATE_LIMIT', 60); // requests per minute
define('ODOO_WEBHOOK_TIMEOUT', 5); // seconds - must respond within this time
define('ODOO_DASHBOARD_STALE_TTL', $odooDashboardStaleEnv !== false ? max(30, (int) $odooDashboardStaleEnv) : 300); // seconds

// Odoo Product API credentials (for /ineco_gc endpoints)
// Credentials must come from env vars only — no hardcoded defaults so the codebase is safe to fork to other tenants.
define('CNY_ODOO_API_USER', getenv('CNY_ODOO_API_USER') ?: (getenv('ODOO_PRODUCTION_API_USER') ?: ''));
define('CNY_ODOO_USER_TOKEN', getenv('CNY_ODOO_USER_TOKEN') ?: (getenv('ODOO_PRODUCTION_USER_TOKEN') ?: ''));

// Gemini AI Chat
define('GEMINI_API_KEY', getenv('GEMINI_API_KEY') ?: '');

// Webhook URL (for Odoo team reference)
define('ODOO_WEBHOOK_URL', APP_URL . '/api/webhook/odoo.php');

// LINE Account Mode for Odoo Integration
// 'shared' = ค้นหา user จากทุก line_account_id ในระบบ
define('ODOO_LINE_ACCOUNT_MODE', 'shared');

// ============================================================================
// Redis Cache Configuration — Redis Cloud (shared ทั้ง odoo + inboxreya)
// Host: redis-13718.fcrce172.us-east-1-1.ec2.cloud.redislabs.com:13718
// ============================================================================
define('REDIS_HOST',     getenv('REDIS_HOST')     ?: 'redis-13718.fcrce172.us-east-1-1.ec2.cloud.redislabs.com');
define('REDIS_PORT',     getenv('REDIS_PORT')     ?: 13718);
define('REDIS_USERNAME', getenv('REDIS_USERNAME') ?: 'default');
define('REDIS_PASSWORD', getenv('REDIS_PASSWORD') ?: '8aOsi5ZlcevxIxkXOFn4b4qshhMTHKC5');
define('REDIS_DB',       getenv('REDIS_DB')       ?: 0);     // DB index (0–15)
define('REDIS_TIMEOUT',  3.0);                               // วินาที (cloud ต้องการนานกว่า local)
define('REDIS_PREFIX',   'cny:');                            // prefix สำหรับทุก key

date_default_timezone_set(TIMEZONE);
