#!/usr/bin/env python3
"""
Generate a seed SQL file for master_products from master_สินค้า.csv.

Reads CSV (UTF-8 with optional BOM, 12-col Thai template) and writes batched
multi-row INSERT statements to database/master_products_seed.sql.

Usage:
    python scripts/generate_master_products_seed.py [INPUT.csv] [OUTPUT.sql]
"""
import csv
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
DEFAULT_IN  = Path(r"C:\Users\Administrator\Downloads\master_สินค้า.csv")
DEFAULT_OUT = ROOT / "database" / "master_products_seed.sql"

# CSV column index → master_products column.
# Excel template column order (0-based after BOM stripping):
#   0 SKU   1 name(th)   2 name(en)   3 manufacturer   4 variant
#   5 generic   6 unit   7 pack_size   8 usage   9 description
#   10 image_url   11 name_en_old(ref — ignored)
COL_SKU, COL_NAME_TH, COL_NAME_EN, COL_MFR, COL_VARIANT = 0, 1, 2, 3, 4
COL_GENERIC, COL_UNIT, COL_PACK, COL_USAGE = 5, 6, 7, 8
COL_DESC, COL_IMG = 9, 10

BATCH = 200  # rows per INSERT statement


def esc(v: str) -> str:
    """MySQL string-literal escape (single quotes + backslash + NUL)."""
    if v is None:
        return "NULL"
    s = str(v).strip()
    if s == "":
        return "NULL"
    s = (
        s.replace("\\", "\\\\")
         .replace("'", "\\'")
         .replace("\x00", "")
         .replace("\r", " ")
         .replace("\n", " ")
    )
    return f"'{s}'"


def main():
    src = Path(sys.argv[1]) if len(sys.argv) > 1 else DEFAULT_IN
    dst = Path(sys.argv[2]) if len(sys.argv) > 2 else DEFAULT_OUT

    if not src.exists():
        print(f"ERROR: source CSV not found: {src}", file=sys.stderr)
        sys.exit(1)

    rows = []
    with open(src, encoding="utf-8-sig", newline="") as fh:
        reader = csv.reader(fh)
        header = next(reader, None)
        if not header:
            print("ERROR: empty CSV", file=sys.stderr)
            sys.exit(1)
        for row in reader:
            if len(row) < 11:
                continue
            sku  = (row[COL_SKU] or "").strip()
            name = (row[COL_NAME_TH] or "").strip()
            if not sku or not name:
                continue
            rows.append({
                "sku":          sku,
                "name":         name,
                "name_en":      (row[COL_NAME_EN] or "").strip(),
                "manufacturer": (row[COL_MFR] or "").strip(),
                "variant":      (row[COL_VARIANT] or "").strip(),
                "generic":      (row[COL_GENERIC] or "").strip(),
                "unit":         (row[COL_UNIT] or "").strip(),
                "pack":         (row[COL_PACK] or "").strip(),
                "usage":        (row[COL_USAGE] or "").strip(),
                "desc":         (row[COL_DESC] or "").strip(),
                "img":          (row[COL_IMG] or "").strip(),
            })

    dst.parent.mkdir(parents=True, exist_ok=True)
    with open(dst, "w", encoding="utf-8", newline="") as out:
        out.write("-- Auto-generated by scripts/generate_master_products_seed.py\n")
        out.write("-- Source: " + str(src) + "\n")
        out.write(f"-- Rows:   {len(rows)}\n")
        out.write("SET NAMES utf8mb4;\n")
        out.write("START TRANSACTION;\n\n")

        cols = (
            "(`sku`, `name`, `name_en`, `manufacturer`, `variant`, `generic_name`, "
            "`unit`, `pack_size`, `usage_instructions`, `description`, `image_url`, `source`)"
        )

        for i in range(0, len(rows), BATCH):
            chunk = rows[i:i + BATCH]
            out.write(f"INSERT INTO `master_products` {cols} VALUES\n")
            value_rows = []
            for r in chunk:
                value_rows.append("(" + ", ".join([
                    esc(r["sku"]),
                    esc(r["name"]),
                    esc(r["name_en"]),
                    esc(r["manufacturer"]),
                    esc(r["variant"]),
                    esc(r["generic"]),
                    esc(r["unit"]),
                    esc(r["pack"]),
                    esc(r["usage"]),
                    esc(r["desc"]),
                    esc(r["img"]),
                    "'cny'",
                ]) + ")")
            out.write(",\n".join(value_rows))
            out.write(
                "\nON DUPLICATE KEY UPDATE\n"
                "  `name`=VALUES(`name`),\n"
                "  `name_en`=VALUES(`name_en`),\n"
                "  `manufacturer`=VALUES(`manufacturer`),\n"
                "  `variant`=VALUES(`variant`),\n"
                "  `generic_name`=VALUES(`generic_name`),\n"
                "  `unit`=VALUES(`unit`),\n"
                "  `pack_size`=VALUES(`pack_size`),\n"
                "  `usage_instructions`=VALUES(`usage_instructions`),\n"
                "  `description`=VALUES(`description`),\n"
                "  `image_url`=VALUES(`image_url`);\n\n"
            )

        out.write("COMMIT;\n")

    print(f"OK: wrote {len(rows)} rows -> {dst}")


if __name__ == "__main__":
    main()
